<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCitiesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('cities', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('province_id');
            $table->unsignedBigInteger('county_id');
            $table->string('name', 50);
            $table->unsignedBigInteger('created_by')->nullable();
            $table->unsignedBigInteger('edited_by')->nullable();
            $table->unsignedBigInteger('deleted_by')->nullable();
        });

        $default_cities = [
            ['province_id' => 1, 'county_id' => 1, 'name' => 'آذرشهر'],
            ['province_id' => 1, 'county_id' => 1, 'name' => 'تیمورلو'],
            ['province_id' => 1, 'county_id' => 1, 'name' => 'گوگان'],
            ['province_id' => 1, 'county_id' => 1, 'name' => 'ممقان'],
            ['province_id' => 1, 'county_id' => 2, 'name' => 'اسکو'],
            ['province_id' => 1, 'county_id' => 2, 'name' => 'ایلخچی'],
            ['province_id' => 1, 'county_id' => 2, 'name' => 'سهند'],
            ['province_id' => 1, 'county_id' => 3, 'name' => 'اهر'],
            ['province_id' => 1, 'county_id' => 3, 'name' => 'هوراند'],
            ['province_id' => 1, 'county_id' => 4, 'name' => 'بستان آباد'],
            ['province_id' => 1, 'county_id' => 4, 'name' => 'تیکمه داش'],
            ['province_id' => 1, 'county_id' => 5, 'name' => 'بناب'],
            ['province_id' => 1, 'county_id' => 6, 'name' => 'باسمنج'],
            ['province_id' => 1, 'county_id' => 6, 'name' => 'تبریز'],
            ['province_id' => 1, 'county_id' => 6, 'name' => 'خسروشاه'],
            ['province_id' => 1, 'county_id' => 6, 'name' => 'سردرود'],
            ['province_id' => 1, 'county_id' => 7, 'name' => 'جلفا'],
            ['province_id' => 1, 'county_id' => 7, 'name' => 'سیه رود'],
            ['province_id' => 1, 'county_id' => 7, 'name' => 'هادیشهر'],
            ['province_id' => 1, 'county_id' => 8, 'name' => 'قره آغاج'],
            ['province_id' => 1, 'county_id' => 9, 'name' => 'خمارلو'],
            ['province_id' => 1, 'county_id' => 10, 'name' => 'دوزدوزان'],
            ['province_id' => 1, 'county_id' => 10, 'name' => 'سراب'],
            ['province_id' => 1, 'county_id' => 10, 'name' => 'شربیان'],
            ['province_id' => 1, 'county_id' => 10, 'name' => 'مهربان'],
            ['province_id' => 1, 'county_id' => 11, 'name' => 'تسوج'],
            ['province_id' => 1, 'county_id' => 11, 'name' => 'خامنه'],
            ['province_id' => 1, 'county_id' => 11, 'name' => 'سیس'],
            ['province_id' => 1, 'county_id' => 11, 'name' => 'شبستر'],
            ['province_id' => 1, 'county_id' => 11, 'name' => 'شرفخانه'],
            ['province_id' => 1, 'county_id' => 11, 'name' => 'شندآباد'],
            ['province_id' => 1, 'county_id' => 11, 'name' => 'صوفیان'],
            ['province_id' => 1, 'county_id' => 11, 'name' => 'کوزه کنان'],
            ['province_id' => 1, 'county_id' => 11, 'name' => 'وایقان'],
            ['province_id' => 1, 'county_id' => 12, 'name' => 'جوان قلعه'],
            ['province_id' => 1, 'county_id' => 12, 'name' => 'عجب شیر'],
            ['province_id' => 1, 'county_id' => 13, 'name' => 'آبش احمد'],
            ['province_id' => 1, 'county_id' => 13, 'name' => 'کلیبر'],
            ['province_id' => 1, 'county_id' => 14, 'name' => 'خداجو (خراجو)'],
            ['province_id' => 1, 'county_id' => 14, 'name' => 'مراغه'],
            ['province_id' => 1, 'county_id' => 15, 'name' => 'بناب مرند'],
            ['province_id' => 1, 'county_id' => 15, 'name' => 'زنوز'],
            ['province_id' => 1, 'county_id' => 15, 'name' => 'کشکسرای'],
            ['province_id' => 1, 'county_id' => 15, 'name' => 'مرند'],
            ['province_id' => 1, 'county_id' => 15, 'name' => 'یامچی'],
            ['province_id' => 1, 'county_id' => 16, 'name' => 'لیلان'],
            ['province_id' => 1, 'county_id' => 16, 'name' => 'مبارک شهر'],
            ['province_id' => 1, 'county_id' => 16, 'name' => 'ملکان'],
            ['province_id' => 1, 'county_id' => 17, 'name' => 'آقکند'],
            ['province_id' => 1, 'county_id' => 17, 'name' => 'اچاچی'],
            ['province_id' => 1, 'county_id' => 17, 'name' => 'ترک'],
            ['province_id' => 1, 'county_id' => 17, 'name' => 'ترکمانچای'],
            ['province_id' => 1, 'county_id' => 17, 'name' => 'میانه'],
            ['province_id' => 1, 'county_id' => 18, 'name' => 'خاروانا'],
            ['province_id' => 1, 'county_id' => 18, 'name' => 'ورزقان'],
            ['province_id' => 1, 'county_id' => 19, 'name' => 'بخشایش'],
            ['province_id' => 1, 'county_id' => 19, 'name' => 'خواجه'],
            ['province_id' => 1, 'county_id' => 19, 'name' => 'زرنق'],
            ['province_id' => 1, 'county_id' => 19, 'name' => 'کلوانق'],
            ['province_id' => 1, 'county_id' => 19, 'name' => 'هریس'],
            ['province_id' => 1, 'county_id' => 20, 'name' => 'نظرکهریزی'],
            ['province_id' => 1, 'county_id' => 20, 'name' => 'هشترود'],
            ['province_id' => 2, 'county_id' => 21, 'name' => 'ارومیه'],
            ['province_id' => 2, 'county_id' => 21, 'name' => 'سرو'],
            ['province_id' => 2, 'county_id' => 21, 'name' => 'سیلوانه'],
            ['province_id' => 2, 'county_id' => 21, 'name' => 'قوشچی'],
            ['province_id' => 2, 'county_id' => 21, 'name' => 'نوشین'],
            ['province_id' => 2, 'county_id' => 22, 'name' => 'اشنویه'],
            ['province_id' => 2, 'county_id' => 22, 'name' => 'نالوس'],
            ['province_id' => 2, 'county_id' => 23, 'name' => 'بوکان'],
            ['province_id' => 2, 'county_id' => 23, 'name' => 'سیمینه'],
            ['province_id' => 2, 'county_id' => 24, 'name' => 'پلدشت'],
            ['province_id' => 2, 'county_id' => 24, 'name' => 'نازک علیا'],
            ['province_id' => 2, 'county_id' => 25, 'name' => 'پیرانشهر'],
            ['province_id' => 2, 'county_id' => 25, 'name' => 'گردکشانه'],
            ['province_id' => 2, 'county_id' => 26, 'name' => 'تکاب'],
            ['province_id' => 2, 'county_id' => 27, 'name' => 'آواجیق'],
            ['province_id' => 2, 'county_id' => 27, 'name' => 'سیه چشمه'],
            ['province_id' => 2, 'county_id' => 28, 'name' => 'قره ضیاءالدین'],
            ['province_id' => 2, 'county_id' => 29, 'name' => 'ایواوغلی'],
            ['province_id' => 2, 'county_id' => 29, 'name' => 'خوی'],
            ['province_id' => 2, 'county_id' => 29, 'name' => 'دیزج دیز'],
            ['province_id' => 2, 'county_id' => 29, 'name' => 'زرآباد'],
            ['province_id' => 2, 'county_id' => 29, 'name' => 'فیرورق'],
            ['province_id' => 2, 'county_id' => 29, 'name' => 'قطور'],
            ['province_id' => 2, 'county_id' => 30, 'name' => 'ربط'],
            ['province_id' => 2, 'county_id' => 30, 'name' => 'سردشت'],
            ['province_id' => 2, 'county_id' => 30, 'name' => 'میرآباد'],
            ['province_id' => 2, 'county_id' => 31, 'name' => 'تازه شهر'],
            ['province_id' => 2, 'county_id' => 31, 'name' => 'سلماس'],
            ['province_id' => 2, 'county_id' => 32, 'name' => 'شاهین دژ'],
            ['province_id' => 2, 'county_id' => 32, 'name' => 'کشاورز'],
            ['province_id' => 2, 'county_id' => 32, 'name' => 'محمودآباد'],
            ['province_id' => 2, 'county_id' => 33, 'name' => 'شوط'],
            ['province_id' => 2, 'county_id' => 33, 'name' => 'مرگنلر'],
            ['province_id' => 2, 'county_id' => 34, 'name' => 'بازرگان'],
            ['province_id' => 2, 'county_id' => 34, 'name' => 'ماکو'],
            ['province_id' => 2, 'county_id' => 35, 'name' => 'خلیفان'],
            ['province_id' => 2, 'county_id' => 35, 'name' => 'مهاباد'],
            ['province_id' => 2, 'county_id' => 36, 'name' => 'باروق'],
            ['province_id' => 2, 'county_id' => 36, 'name' => 'چهاربرج'],
            ['province_id' => 2, 'county_id' => 36, 'name' => 'میاندوآب'],
            ['province_id' => 2, 'county_id' => 37, 'name' => 'محمدیار'],
            ['province_id' => 2, 'county_id' => 37, 'name' => 'نقده'],
            ['province_id' => 3, 'county_id' => 38, 'name' => 'اردبیل'],
            ['province_id' => 3, 'county_id' => 38, 'name' => 'هیر'],
            ['province_id' => 3, 'county_id' => 39, 'name' => 'بیله سوار'],
            ['province_id' => 3, 'county_id' => 39, 'name' => 'جعفرآباد'],
            ['province_id' => 3, 'county_id' => 40, 'name' => 'اسلام اباد'],
            ['province_id' => 3, 'county_id' => 40, 'name' => 'اصلاندوز'],
            ['province_id' => 3, 'county_id' => 40, 'name' => 'پارس آباد'],
            ['province_id' => 3, 'county_id' => 40, 'name' => 'تازه کند'],
            ['province_id' => 3, 'county_id' => 41, 'name' => 'خلخال'],
            ['province_id' => 3, 'county_id' => 41, 'name' => 'کلور'],
            ['province_id' => 3, 'county_id' => 41, 'name' => 'هشتجین'],
            ['province_id' => 3, 'county_id' => 42, 'name' => 'سرعین'],
            ['province_id' => 3, 'county_id' => 43, 'name' => 'گیوی'],
            ['province_id' => 3, 'county_id' => 44, 'name' => 'تازه کندانگوت'],
            ['province_id' => 3, 'county_id' => 44, 'name' => 'گرمی'],
            ['province_id' => 3, 'county_id' => 45, 'name' => 'رضی'],
            ['province_id' => 3, 'county_id' => 45, 'name' => 'فخراباد'],
            ['province_id' => 3, 'county_id' => 45, 'name' => 'قصابه'],
            ['province_id' => 3, 'county_id' => 45, 'name' => 'لاهرود'],
            ['province_id' => 3, 'county_id' => 45, 'name' => 'مرادلو'],
            ['province_id' => 3, 'county_id' => 45, 'name' => 'مشگین شهر'],
            ['province_id' => 3, 'county_id' => 46, 'name' => 'آبی بیگلو'],
            ['province_id' => 3, 'county_id' => 46, 'name' => 'عنبران'],
            ['province_id' => 3, 'county_id' => 46, 'name' => 'نمین'],
            ['province_id' => 3, 'county_id' => 47, 'name' => 'کوراییم'],
            ['province_id' => 3, 'county_id' => 47, 'name' => 'نیر'],
            ['province_id' => 4, 'county_id' => 48, 'name' => 'آران وبیدگل'],
            ['province_id' => 4, 'county_id' => 48, 'name' => 'ابوزیدآباد'],
            ['province_id' => 4, 'county_id' => 48, 'name' => 'سفیدشهر'],
            ['province_id' => 4, 'county_id' => 48, 'name' => 'نوش آباد'],
            ['province_id' => 4, 'county_id' => 49, 'name' => 'اردستان'],
            ['province_id' => 4, 'county_id' => 49, 'name' => 'زواره'],
            ['province_id' => 4, 'county_id' => 49, 'name' => 'مهاباد'],
            ['province_id' => 4, 'county_id' => 50, 'name' => 'اژیه'],
            ['province_id' => 4, 'county_id' => 50, 'name' => 'اصفهان'],
            ['province_id' => 4, 'county_id' => 50, 'name' => 'بهارستان'],
            ['province_id' => 4, 'county_id' => 50, 'name' => 'تودشک'],
            ['province_id' => 4, 'county_id' => 50, 'name' => 'حسن اباد'],
            ['province_id' => 4, 'county_id' => 50, 'name' => 'زیار'],
            ['province_id' => 4, 'county_id' => 50, 'name' => 'سجزی'],
            ['province_id' => 4, 'county_id' => 50, 'name' => 'قهجاورستان'],
            ['province_id' => 4, 'county_id' => 50, 'name' => 'کوهپایه'],
            ['province_id' => 4, 'county_id' => 50, 'name' => 'محمدآباد'],
            ['province_id' => 4, 'county_id' => 50, 'name' => 'نصرآباد'],
            ['province_id' => 4, 'county_id' => 50, 'name' => 'نیک آباد'],
            ['province_id' => 4, 'county_id' => 50, 'name' => 'ورزنه'],
            ['province_id' => 4, 'county_id' => 50, 'name' => 'هرند'],
            ['province_id' => 4, 'county_id' => 51, 'name' => 'حبیب آباد'],
            ['province_id' => 4, 'county_id' => 51, 'name' => 'خورزوق'],
            ['province_id' => 4, 'county_id' => 51, 'name' => 'دستگرد'],
            ['province_id' => 4, 'county_id' => 51, 'name' => 'دولت آباد'],
            ['province_id' => 4, 'county_id' => 51, 'name' => 'سین'],
            ['province_id' => 4, 'county_id' => 51, 'name' => 'شاپورآباد'],
            ['province_id' => 4, 'county_id' => 51, 'name' => 'کمشچه'],
            ['province_id' => 4, 'county_id' => 52, 'name' => 'افوس'],
            ['province_id' => 4, 'county_id' => 52, 'name' => 'بویین ومیاندشت'],
            ['province_id' => 4, 'county_id' => 53, 'name' => 'تیران'],
            ['province_id' => 4, 'county_id' => 53, 'name' => 'رضوانشهر'],
            ['province_id' => 4, 'county_id' => 53, 'name' => 'عسگران'],
            ['province_id' => 4, 'county_id' => 54, 'name' => 'چادگان'],
            ['province_id' => 4, 'county_id' => 54, 'name' => 'رزوه'],
            ['province_id' => 4, 'county_id' => 55, 'name' => 'اصغرآباد'],
            ['province_id' => 4, 'county_id' => 55, 'name' => 'خمینی شهر'],
            ['province_id' => 4, 'county_id' => 55, 'name' => 'درچه'],
            ['province_id' => 4, 'county_id' => 55, 'name' => 'کوشک'],
            ['province_id' => 4, 'county_id' => 56, 'name' => 'خوانسار'],
            ['province_id' => 4, 'county_id' => 57, 'name' => 'جندق'],
            ['province_id' => 4, 'county_id' => 57, 'name' => 'خور'],
            ['province_id' => 4, 'county_id' => 57, 'name' => 'فرخی'],
            ['province_id' => 4, 'county_id' => 58, 'name' => 'دهاقان'],
            ['province_id' => 4, 'county_id' => 58, 'name' => 'گلشن'],
            ['province_id' => 4, 'county_id' => 59, 'name' => 'حنا'],
            ['province_id' => 4, 'county_id' => 59, 'name' => 'سمیرم'],
            ['province_id' => 4, 'county_id' => 59, 'name' => 'کمه'],
            ['province_id' => 4, 'county_id' => 59, 'name' => 'ونک'],
            ['province_id' => 4, 'county_id' => 60, 'name' => 'شاهین شهر'],
            ['province_id' => 4, 'county_id' => 60, 'name' => 'گرگاب'],
            ['province_id' => 4, 'county_id' => 60, 'name' => 'گزبرخوار'],
            ['province_id' => 4, 'county_id' => 60, 'name' => 'لای بید'],
            ['province_id' => 4, 'county_id' => 60, 'name' => 'میمه'],
            ['province_id' => 4, 'county_id' => 60, 'name' => 'وزوان'],
            ['province_id' => 4, 'county_id' => 61, 'name' => 'شهرضا'],
            ['province_id' => 4, 'county_id' => 61, 'name' => 'منظریه'],
            ['province_id' => 4, 'county_id' => 62, 'name' => 'داران'],
            ['province_id' => 4, 'county_id' => 62, 'name' => 'دامنه'],
            ['province_id' => 4, 'county_id' => 63, 'name' => 'برف انبار'],
            ['province_id' => 4, 'county_id' => 63, 'name' => 'فریدونشهر'],
            ['province_id' => 4, 'county_id' => 64, 'name' => 'ابریشم'],
            ['province_id' => 4, 'county_id' => 64, 'name' => 'ایمانشهر'],
            ['province_id' => 4, 'county_id' => 64, 'name' => 'بهاران شهر'],
            ['province_id' => 4, 'county_id' => 64, 'name' => 'پیربکران'],
            ['province_id' => 4, 'county_id' => 64, 'name' => 'زازران'],
            ['province_id' => 4, 'county_id' => 64, 'name' => 'فلاورجان'],
            ['province_id' => 4, 'county_id' => 64, 'name' => 'قهدریجان'],
            ['province_id' => 4, 'county_id' => 64, 'name' => 'کلیشادوسودرجان'],
            ['province_id' => 4, 'county_id' => 65, 'name' => 'برزک'],
            ['province_id' => 4, 'county_id' => 65, 'name' => 'جوشقان قالی'],
            ['province_id' => 4, 'county_id' => 65, 'name' => 'قمصر'],
            ['province_id' => 4, 'county_id' => 65, 'name' => 'کاشان'],
            ['province_id' => 4, 'county_id' => 65, 'name' => 'کامو و چوگان'],
            ['province_id' => 4, 'county_id' => 65, 'name' => 'مشکات'],
            ['province_id' => 4, 'county_id' => 65, 'name' => 'نیاسر'],
            ['province_id' => 4, 'county_id' => 66, 'name' => 'گلپایگان'],
            ['province_id' => 4, 'county_id' => 66, 'name' => 'گلشهر'],
            ['province_id' => 4, 'county_id' => 66, 'name' => 'گوگد'],
            ['province_id' => 4, 'county_id' => 67, 'name' => 'باغ بهادران'],
            ['province_id' => 4, 'county_id' => 67, 'name' => 'باغشاد'],
            ['province_id' => 4, 'county_id' => 67, 'name' => 'چرمهین'],
            ['province_id' => 4, 'county_id' => 67, 'name' => 'چمگردان'],
            ['province_id' => 4, 'county_id' => 67, 'name' => 'زاینده رود'],
            ['province_id' => 4, 'county_id' => 67, 'name' => 'زرین شهر'],
            ['province_id' => 4, 'county_id' => 67, 'name' => 'سده لنجان'],
            ['province_id' => 4, 'county_id' => 67, 'name' => 'فولادشهر'],
            ['province_id' => 4, 'county_id' => 67, 'name' => 'ورنامخواست'],
            ['province_id' => 4, 'county_id' => 68, 'name' => 'دیزیچه'],
            ['province_id' => 4, 'county_id' => 68, 'name' => 'زیباشهر'],
            ['province_id' => 4, 'county_id' => 68, 'name' => 'طالخونچه'],
            ['province_id' => 4, 'county_id' => 68, 'name' => 'کرکوند'],
            ['province_id' => 4, 'county_id' => 68, 'name' => 'مبارکه'],
            ['province_id' => 4, 'county_id' => 68, 'name' => 'مجلسی'],
            ['province_id' => 4, 'county_id' => 69, 'name' => 'انارک'],
            ['province_id' => 4, 'county_id' => 69, 'name' => 'بافران'],
            ['province_id' => 4, 'county_id' => 69, 'name' => 'نایین'],
            ['province_id' => 4, 'county_id' => 70, 'name' => 'جوزدان'],
            ['province_id' => 4, 'county_id' => 70, 'name' => 'دهق'],
            ['province_id' => 4, 'county_id' => 70, 'name' => 'علویجه'],
            ['province_id' => 4, 'county_id' => 70, 'name' => 'کهریزسنگ'],
            ['province_id' => 4, 'county_id' => 70, 'name' => 'گلدشت'],
            ['province_id' => 4, 'county_id' => 70, 'name' => 'نجف آباد'],
            ['province_id' => 4, 'county_id' => 71, 'name' => 'بادرود'],
            ['province_id' => 4, 'county_id' => 71, 'name' => 'خالدآباد'],
            ['province_id' => 4, 'county_id' => 71, 'name' => 'طرق رود'],
            ['province_id' => 4, 'county_id' => 71, 'name' => 'نطنز'],
            ['province_id' => 5, 'county_id' => 72, 'name' => 'اشتهارد'],
            ['province_id' => 5, 'county_id' => 73, 'name' => 'چهارباغ'],
            ['province_id' => 5, 'county_id' => 73, 'name' => 'شهرجدیدهشتگرد'],
            ['province_id' => 5, 'county_id' => 73, 'name' => 'کوهسار'],
            ['province_id' => 5, 'county_id' => 73, 'name' => 'گلسار'],
            ['province_id' => 5, 'county_id' => 73, 'name' => 'هشتگرد'],
            ['province_id' => 5, 'county_id' => 74, 'name' => 'طالقان'],
            ['province_id' => 5, 'county_id' => 75, 'name' => 'فردیس'],
            ['province_id' => 5, 'county_id' => 75, 'name' => 'مشکین دشت'],
            ['province_id' => 5, 'county_id' => 76, 'name' => 'آسارا'],
            ['province_id' => 5, 'county_id' => 76, 'name' => 'کرج'],
            ['province_id' => 5, 'county_id' => 76, 'name' => 'کمال شهر'],
            ['province_id' => 5, 'county_id' => 76, 'name' => 'گرمدره'],
            ['province_id' => 5, 'county_id' => 76, 'name' => 'ماهدشت'],
            ['province_id' => 5, 'county_id' => 76, 'name' => 'محمدشهر'],
            ['province_id' => 5, 'county_id' => 77, 'name' => 'تنکمان'],
            ['province_id' => 5, 'county_id' => 77, 'name' => 'نظرآباد'],
            ['province_id' => 6, 'county_id' => 78, 'name' => 'آبدانان'],
            ['province_id' => 6, 'county_id' => 78, 'name' => 'سراب باغ'],
            ['province_id' => 6, 'county_id' => 78, 'name' => 'مورموری'],
            ['province_id' => 6, 'county_id' => 79, 'name' => 'ایلام'],
            ['province_id' => 6, 'county_id' => 79, 'name' => 'چوار'],
            ['province_id' => 6, 'county_id' => 80, 'name' => 'ایوان'],
            ['province_id' => 6, 'county_id' => 80, 'name' => 'زرنه'],
            ['province_id' => 6, 'county_id' => 81, 'name' => 'بدره'],
            ['province_id' => 6, 'county_id' => 82, 'name' => 'آسمان آباد'],
            ['province_id' => 6, 'county_id' => 82, 'name' => 'بلاوه'],
            ['province_id' => 6, 'county_id' => 82, 'name' => 'توحید'],
            ['province_id' => 6, 'county_id' => 82, 'name' => 'سرابله'],
            ['province_id' => 6, 'county_id' => 82, 'name' => 'شباب'],
            ['province_id' => 6, 'county_id' => 83, 'name' => 'دره شهر'],
            ['province_id' => 6, 'county_id' => 83, 'name' => 'ماژین'],
            ['province_id' => 6, 'county_id' => 84, 'name' => 'پهله'],
            ['province_id' => 6, 'county_id' => 84, 'name' => 'دهلران'],
            ['province_id' => 6, 'county_id' => 84, 'name' => 'موسیان'],
            ['province_id' => 6, 'county_id' => 84, 'name' => 'میمه'],
            ['province_id' => 6, 'county_id' => 85, 'name' => 'لومار'],
            ['province_id' => 6, 'county_id' => 86, 'name' => 'ارکواز'],
            ['province_id' => 6, 'county_id' => 86, 'name' => 'دلگشا'],
            ['province_id' => 6, 'county_id' => 86, 'name' => 'مهر'],
            ['province_id' => 6, 'county_id' => 87, 'name' => 'صالح آباد'],
            ['province_id' => 6, 'county_id' => 87, 'name' => 'مهران'],
            ['province_id' => 7, 'county_id' => 88, 'name' => 'بوشهر'],
            ['province_id' => 7, 'county_id' => 88, 'name' => 'چغادک'],
            ['province_id' => 7, 'county_id' => 88, 'name' => 'خارک'],
            ['province_id' => 7, 'county_id' => 88, 'name' => 'عالی شهر'],
            ['province_id' => 7, 'county_id' => 89, 'name' => 'آباد'],
            ['province_id' => 7, 'county_id' => 89, 'name' => 'اهرم'],
            ['province_id' => 7, 'county_id' => 89, 'name' => 'دلوار'],
            ['province_id' => 7, 'county_id' => 90, 'name' => 'انارستان'],
            ['province_id' => 7, 'county_id' => 90, 'name' => 'جم'],
            ['province_id' => 7, 'county_id' => 90, 'name' => 'ریز'],
            ['province_id' => 7, 'county_id' => 91, 'name' => 'آب پخش'],
            ['province_id' => 7, 'county_id' => 91, 'name' => 'برازجان'],
            ['province_id' => 7, 'county_id' => 91, 'name' => 'بوشکان'],
            ['province_id' => 7, 'county_id' => 91, 'name' => 'تنگ ارم'],
            ['province_id' => 7, 'county_id' => 91, 'name' => 'دالکی'],
            ['province_id' => 7, 'county_id' => 91, 'name' => 'سعد آباد'],
            ['province_id' => 7, 'county_id' => 91, 'name' => 'شبانکاره'],
            ['province_id' => 7, 'county_id' => 91, 'name' => 'کلمه'],
            ['province_id' => 7, 'county_id' => 91, 'name' => 'وحدتیه'],
            ['province_id' => 7, 'county_id' => 92, 'name' => 'بادوله'],
            ['province_id' => 7, 'county_id' => 92, 'name' => 'خورموج'],
            ['province_id' => 7, 'county_id' => 92, 'name' => 'شنبه'],
            ['province_id' => 7, 'county_id' => 92, 'name' => 'کاکی'],
            ['province_id' => 7, 'county_id' => 93, 'name' => 'آبدان'],
            ['province_id' => 7, 'county_id' => 93, 'name' => 'بردخون'],
            ['province_id' => 7, 'county_id' => 93, 'name' => 'بردستان'],
            ['province_id' => 7, 'county_id' => 93, 'name' => 'بندردیر'],
            ['province_id' => 7, 'county_id' => 93, 'name' => 'دوراهک'],
            ['province_id' => 7, 'county_id' => 94, 'name' => 'امام حسن'],
            ['province_id' => 7, 'county_id' => 94, 'name' => 'بندردیلم'],
            ['province_id' => 7, 'county_id' => 95, 'name' => 'عسلویه'],
            ['province_id' => 7, 'county_id' => 95, 'name' => 'نخل تقی'],
            ['province_id' => 7, 'county_id' => 95, 'name' => 'شیرینو'],
            ['province_id' => 7, 'county_id' => 96, 'name' => 'بندرکنگان'],
            ['province_id' => 7, 'county_id' => 96, 'name' => 'بنک'],
            ['province_id' => 7, 'county_id' => 96, 'name' => 'سیراف'],
            ['province_id' => 7, 'county_id' => 97, 'name' => 'بندرریگ'],
            ['province_id' => 7, 'county_id' => 97, 'name' => 'بندرگناوه'],
            ['province_id' => 8, 'county_id' => 98, 'name' => 'احمد آباد مستوفی'],
            ['province_id' => 8, 'county_id' => 98, 'name' => 'اسلامشهر'],
            ['province_id' => 8, 'county_id' => 98, 'name' => 'چهاردانگه'],
            ['province_id' => 8, 'county_id' => 99, 'name' => 'صالحیه'],
            ['province_id' => 8, 'county_id' => 99, 'name' => 'گلستان'],
            ['province_id' => 8, 'county_id' => 99, 'name' => 'نسیم شهر'],
            ['province_id' => 8, 'county_id' => 100, 'name' => 'پاکدشت'],
            ['province_id' => 8, 'county_id' => 100, 'name' => 'شریف آباد'],
            ['province_id' => 8, 'county_id' => 100, 'name' => 'فرون اباد'],
            ['province_id' => 8, 'county_id' => 101, 'name' => 'بومهن'],
            ['province_id' => 8, 'county_id' => 101, 'name' => 'پردیس'],
            ['province_id' => 8, 'county_id' => 102, 'name' => 'پیشوا'],
            ['province_id' => 8, 'county_id' => 103, 'name' => 'تهران'],
            ['province_id' => 8, 'county_id' => 104, 'name' => 'آبسرد'],
            ['province_id' => 8, 'county_id' => 104, 'name' => 'آبعلی'],
            ['province_id' => 8, 'county_id' => 104, 'name' => 'دماوند'],
            ['province_id' => 8, 'county_id' => 104, 'name' => 'رودهن'],
            ['province_id' => 8, 'county_id' => 104, 'name' => 'کیلان'],
            ['province_id' => 8, 'county_id' => 105, 'name' => 'پرند'],
            ['province_id' => 8, 'county_id' => 105, 'name' => 'رباطکریم'],
            ['province_id' => 8, 'county_id' => 105, 'name' => 'نصیرشهر'],
            ['province_id' => 8, 'county_id' => 106, 'name' => 'باقرشهر'],
            ['province_id' => 8, 'county_id' => 106, 'name' => 'حسن آباد'],
            ['province_id' => 8, 'county_id' => 106, 'name' => 'ری'],
            ['province_id' => 8, 'county_id' => 106, 'name' => 'کهریزک'],
            ['province_id' => 8, 'county_id' => 107, 'name' => 'تجریش'],
            ['province_id' => 8, 'county_id' => 107, 'name' => 'شمشک'],
            ['province_id' => 8, 'county_id' => 107, 'name' => 'فشم'],
            ['province_id' => 8, 'county_id' => 107, 'name' => 'لواسان'],
            ['province_id' => 8, 'county_id' => 108, 'name' => 'اندیشه'],
            ['province_id' => 8, 'county_id' => 108, 'name' => 'باغستان'],
            ['province_id' => 8, 'county_id' => 108, 'name' => 'شاهدشهر'],
            ['province_id' => 8, 'county_id' => 108, 'name' => 'شهریار'],
            ['province_id' => 8, 'county_id' => 108, 'name' => 'صباشهر'],
            ['province_id' => 8, 'county_id' => 108, 'name' => 'فردوسیه'],
            ['province_id' => 8, 'county_id' => 108, 'name' => 'وحیدیه'],
            ['province_id' => 8, 'county_id' => 109, 'name' => 'ارجمند'],
            ['province_id' => 8, 'county_id' => 109, 'name' => 'فیروزکوه'],
            ['province_id' => 8, 'county_id' => 110, 'name' => 'قدس'],
            ['province_id' => 8, 'county_id' => 111, 'name' => 'قرچک'],
            ['province_id' => 8, 'county_id' => 112, 'name' => 'صفادشت'],
            ['province_id' => 8, 'county_id' => 112, 'name' => 'ملارد'],
            ['province_id' => 8, 'county_id' => 113, 'name' => 'جوادآباد'],
            ['province_id' => 8, 'county_id' => 113, 'name' => 'ورامین'],
            ['province_id' => 9, 'county_id' => 114, 'name' => 'اردل'],
            ['province_id' => 9, 'county_id' => 114, 'name' => 'دشتک'],
            ['province_id' => 9, 'county_id' => 114, 'name' => 'سرخون'],
            ['province_id' => 9, 'county_id' => 114, 'name' => 'کاج'],
            ['province_id' => 9, 'county_id' => 115, 'name' => 'بروجن'],
            ['province_id' => 9, 'county_id' => 115, 'name' => 'بلداجی'],
            ['province_id' => 9, 'county_id' => 115, 'name' => 'سفیددشت'],
            ['province_id' => 9, 'county_id' => 115, 'name' => 'فرادبنه'],
            ['province_id' => 9, 'county_id' => 115, 'name' => 'گندمان'],
            ['province_id' => 9, 'county_id' => 115, 'name' => 'نقنه'],
            ['province_id' => 9, 'county_id' => 116, 'name' => 'بن'],
            ['province_id' => 9, 'county_id' => 116, 'name' => 'وردنجان'],
            ['province_id' => 9, 'county_id' => 117, 'name' => 'سامان'],
            ['province_id' => 9, 'county_id' => 118, 'name' => 'سودجان'],
            ['province_id' => 9, 'county_id' => 118, 'name' => 'سورشجان'],
            ['province_id' => 9, 'county_id' => 118, 'name' => 'شهرکرد'],
            ['province_id' => 9, 'county_id' => 118, 'name' => 'طاقانک'],
            ['province_id' => 9, 'county_id' => 118, 'name' => 'فرخ شهر'],
            ['province_id' => 9, 'county_id' => 118, 'name' => 'کیان'],
            ['province_id' => 9, 'county_id' => 118, 'name' => 'نافچ'],
            ['province_id' => 9, 'county_id' => 118, 'name' => 'هارونی'],
            ['province_id' => 9, 'county_id' => 118, 'name' => 'هفشجان'],
            ['province_id' => 9, 'county_id' => 119, 'name' => 'باباحیدر'],
            ['province_id' => 9, 'county_id' => 119, 'name' => 'پردنجان'],
            ['province_id' => 9, 'county_id' => 119, 'name' => 'جونقان'],
            ['province_id' => 9, 'county_id' => 119, 'name' => 'چلیچه'],
            ['province_id' => 9, 'county_id' => 119, 'name' => 'فارسان'],
            ['province_id' => 9, 'county_id' => 119, 'name' => 'گوجان'],
            ['province_id' => 9, 'county_id' => 120, 'name' => 'بازفت'],
            ['province_id' => 9, 'county_id' => 120, 'name' => 'چلگرد'],
            ['province_id' => 9, 'county_id' => 120, 'name' => 'صمصامی'],
            ['province_id' => 9, 'county_id' => 121, 'name' => 'دستنا'],
            ['province_id' => 9, 'county_id' => 121, 'name' => 'شلمزار'],
            ['province_id' => 9, 'county_id' => 121, 'name' => 'گهرو'],
            ['province_id' => 9, 'county_id' => 121, 'name' => 'ناغان'],
            ['province_id' => 9, 'county_id' => 122, 'name' => 'آلونی'],
            ['province_id' => 9, 'county_id' => 122, 'name' => 'سردشت'],
            ['province_id' => 9, 'county_id' => 122, 'name' => 'لردگان'],
            ['province_id' => 9, 'county_id' => 122, 'name' => 'مال خلیفه'],
            ['province_id' => 9, 'county_id' => 122, 'name' => 'منج'],
            ['province_id' => 10, 'county_id' => 123, 'name' => 'ارسک'],
            ['province_id' => 10, 'county_id' => 123, 'name' => 'بشرویه'],
            ['province_id' => 10, 'county_id' => 124, 'name' => 'بیرجند'],
            ['province_id' => 10, 'county_id' => 125, 'name' => 'خوسف'],
            ['province_id' => 10, 'county_id' => 125, 'name' => 'محمدشهر'],
            ['province_id' => 10, 'county_id' => 126, 'name' => 'اسدیه'],
            ['province_id' => 10, 'county_id' => 126, 'name' => 'طبس مسینا'],
            ['province_id' => 10, 'county_id' => 126, 'name' => 'قهستان'],
            ['province_id' => 10, 'county_id' => 126, 'name' => 'گزیک'],
            ['province_id' => 10, 'county_id' => 127, 'name' => 'حاجی آباد'],
            ['province_id' => 10, 'county_id' => 127, 'name' => 'زهان'],
            ['province_id' => 10, 'county_id' => 128, 'name' => 'آیسک'],
            ['province_id' => 10, 'county_id' => 128, 'name' => 'سرایان'],
            ['province_id' => 10, 'county_id' => 128, 'name' => 'سه قلعه'],
            ['province_id' => 10, 'county_id' => 129, 'name' => 'سربیشه'],
            ['province_id' => 10, 'county_id' => 129, 'name' => 'مود'],
            ['province_id' => 10, 'county_id' => 130, 'name' => 'دیهوک'],
            ['province_id' => 10, 'county_id' => 130, 'name' => 'طبس'],
            ['province_id' => 10, 'county_id' => 130, 'name' => 'عشق آباد'],
            ['province_id' => 10, 'county_id' => 131, 'name' => 'اسلامیه'],
            ['province_id' => 10, 'county_id' => 131, 'name' => 'فردوس'],
            ['province_id' => 10, 'county_id' => 132, 'name' => 'آرین شهر'],
            ['province_id' => 10, 'county_id' => 132, 'name' => 'اسفدن'],
            ['province_id' => 10, 'county_id' => 132, 'name' => 'خضری دشت بیاض'],
            ['province_id' => 10, 'county_id' => 132, 'name' => 'قاین'],
            ['province_id' => 10, 'county_id' => 132, 'name' => 'نیمبلوک'],
            ['province_id' => 10, 'county_id' => 133, 'name' => 'شوسف'],
            ['province_id' => 10, 'county_id' => 133, 'name' => 'نهبندان'],
            ['province_id' => 11, 'county_id' => 134, 'name' => 'باخرز'],
            ['province_id' => 11, 'county_id' => 135, 'name' => 'بجستان'],
            ['province_id' => 11, 'county_id' => 135, 'name' => 'یونسی'],
            ['province_id' => 11, 'county_id' => 136, 'name' => 'انابد'],
            ['province_id' => 11, 'county_id' => 136, 'name' => 'بردسکن'],
            ['province_id' => 11, 'county_id' => 136, 'name' => 'شهراباد'],
            ['province_id' => 11, 'county_id' => 137, 'name' => 'شاندیز'],
            ['province_id' => 11, 'county_id' => 137, 'name' => 'طرقبه'],
            ['province_id' => 11, 'county_id' => 138, 'name' => 'تایباد'],
            ['province_id' => 11, 'county_id' => 138, 'name' => 'کاریز'],
            ['province_id' => 11, 'county_id' => 138, 'name' => 'مشهدریزه'],
            ['province_id' => 11, 'county_id' => 139, 'name' => 'احمدابادصولت'],
            ['province_id' => 11, 'county_id' => 139, 'name' => 'تربت جام'],
            ['province_id' => 11, 'county_id' => 139, 'name' => 'صالح آباد'],
            ['province_id' => 11, 'county_id' => 139, 'name' => 'نصرآباد'],
            ['province_id' => 11, 'county_id' => 139, 'name' => 'نیل شهر'],
            ['province_id' => 11, 'county_id' => 140, 'name' => 'بایک'],
            ['province_id' => 11, 'county_id' => 140, 'name' => 'تربت حیدریه'],
            ['province_id' => 11, 'county_id' => 140, 'name' => 'رباط سنگ'],
            ['province_id' => 11, 'county_id' => 140, 'name' => 'کدکن'],
            ['province_id' => 11, 'county_id' => 141, 'name' => 'جغتای'],
            ['province_id' => 11, 'county_id' => 142, 'name' => 'نقاب'],
            ['province_id' => 11, 'county_id' => 143, 'name' => 'چناران'],
            ['province_id' => 11, 'county_id' => 143, 'name' => 'گلبهار'],
            ['province_id' => 11, 'county_id' => 143, 'name' => 'گلمکان'],
            ['province_id' => 11, 'county_id' => 144, 'name' => 'خلیل آباد'],
            ['province_id' => 11, 'county_id' => 144, 'name' => 'کندر'],
            ['province_id' => 11, 'county_id' => 145, 'name' => 'خواف'],
            ['province_id' => 11, 'county_id' => 145, 'name' => 'سلامی'],
            ['province_id' => 11, 'county_id' => 145, 'name' => 'سنگان'],
            ['province_id' => 11, 'county_id' => 145, 'name' => 'قاسم آباد'],
            ['province_id' => 11, 'county_id' => 145, 'name' => 'نشتیفان'],
            ['province_id' => 11, 'county_id' => 146, 'name' => 'سلطان آباد'],
            ['province_id' => 11, 'county_id' => 147, 'name' => 'داورزن'],
            ['province_id' => 11, 'county_id' => 148, 'name' => 'چاپشلو'],
            ['province_id' => 11, 'county_id' => 148, 'name' => 'درگز'],
            ['province_id' => 11, 'county_id' => 148, 'name' => 'لطف آباد'],
            ['province_id' => 11, 'county_id' => 148, 'name' => 'نوخندان'],
            ['province_id' => 11, 'county_id' => 149, 'name' => 'جنگل'],
            ['province_id' => 11, 'county_id' => 149, 'name' => 'رشتخوار'],
            ['province_id' => 11, 'county_id' => 150, 'name' => 'دولت آباد'],
            ['province_id' => 11, 'county_id' => 151, 'name' => 'روداب'],
            ['province_id' => 11, 'county_id' => 151, 'name' => 'سبزوار'],
            ['province_id' => 11, 'county_id' => 151, 'name' => 'ششتمد'],
            ['province_id' => 11, 'county_id' => 152, 'name' => 'سرخس'],
            ['province_id' => 11, 'county_id' => 152, 'name' => 'مزدآوند'],
            ['province_id' => 11, 'county_id' => 153, 'name' => 'سفیدسنگ'],
            ['province_id' => 11, 'county_id' => 153, 'name' => 'فرهادگرد'],
            ['province_id' => 11, 'county_id' => 153, 'name' => 'فریمان'],
            ['province_id' => 11, 'county_id' => 153, 'name' => 'قلندرآباد'],
            ['province_id' => 11, 'county_id' => 154, 'name' => 'فیروزه'],
            ['province_id' => 11, 'county_id' => 154, 'name' => 'همت آباد'],
            ['province_id' => 11, 'county_id' => 155, 'name' => 'باجگیران'],
            ['province_id' => 11, 'county_id' => 155, 'name' => 'قوچان'],
            ['province_id' => 11, 'county_id' => 156, 'name' => 'ریوش'],
            ['province_id' => 11, 'county_id' => 156, 'name' => 'کاشمر'],
            ['province_id' => 11, 'county_id' => 157, 'name' => 'شهرزو'],
            ['province_id' => 11, 'county_id' => 157, 'name' => 'کلات'],
            ['province_id' => 11, 'county_id' => 158, 'name' => 'بیدخت'],
            ['province_id' => 11, 'county_id' => 158, 'name' => 'کاخک'],
            ['province_id' => 11, 'county_id' => 158, 'name' => 'گناباد'],
            ['province_id' => 11, 'county_id' => 159, 'name' => 'رضویه'],
            ['province_id' => 11, 'county_id' => 159, 'name' => 'مشهد'],
            ['province_id' => 11, 'county_id' => 159, 'name' => 'مشهد ثامن'],
            ['province_id' => 11, 'county_id' => 159, 'name' => 'ملک آباد'],
            ['province_id' => 11, 'county_id' => 160, 'name' => 'شادمهر'],
            ['province_id' => 11, 'county_id' => 160, 'name' => 'فیض آباد'],
            ['province_id' => 11, 'county_id' => 161, 'name' => 'بار'],
            ['province_id' => 11, 'county_id' => 161, 'name' => 'چکنه'],
            ['province_id' => 11, 'county_id' => 161, 'name' => 'خرو'],
            ['province_id' => 11, 'county_id' => 161, 'name' => 'درود'],
            ['province_id' => 11, 'county_id' => 161, 'name' => 'عشق آباد'],
            ['province_id' => 11, 'county_id' => 161, 'name' => 'قدمگاه'],
            ['province_id' => 11, 'county_id' => 161, 'name' => 'نیشابور'],
            ['province_id' => 12, 'county_id' => 162, 'name' => 'اسفراین'],
            ['province_id' => 12, 'county_id' => 162, 'name' => 'صفی آباد'],
            ['province_id' => 12, 'county_id' => 163, 'name' => 'بجنورد'],
            ['province_id' => 12, 'county_id' => 163, 'name' => 'چناران شهر'],
            ['province_id' => 12, 'county_id' => 163, 'name' => 'حصارگرمخان'],
            ['province_id' => 12, 'county_id' => 164, 'name' => 'جاجرم'],
            ['province_id' => 12, 'county_id' => 164, 'name' => 'سنخواست'],
            ['province_id' => 12, 'county_id' => 164, 'name' => 'شوقان'],
            ['province_id' => 12, 'county_id' => 165, 'name' => 'راز'],
            ['province_id' => 12, 'county_id' => 166, 'name' => 'زیارت'],
            ['province_id' => 12, 'county_id' => 166, 'name' => 'شیروان'],
            ['province_id' => 12, 'county_id' => 166, 'name' => 'قوشخانه'],
            ['province_id' => 12, 'county_id' => 166, 'name' => 'لوجلی'],
            ['province_id' => 12, 'county_id' => 167, 'name' => 'تیتکانلو'],
            ['province_id' => 12, 'county_id' => 167, 'name' => 'فاروج'],
            ['province_id' => 12, 'county_id' => 168, 'name' => 'ایور'],
            ['province_id' => 12, 'county_id' => 168, 'name' => 'درق'],
            ['province_id' => 12, 'county_id' => 168, 'name' => 'گرمه'],
            ['province_id' => 12, 'county_id' => 169, 'name' => 'آشخانه'],
            ['province_id' => 12, 'county_id' => 169, 'name' => 'آوا'],
            ['province_id' => 12, 'county_id' => 169, 'name' => 'پیش قلعه'],
            ['province_id' => 12, 'county_id' => 169, 'name' => 'قاضی'],
            ['province_id' => 13, 'county_id' => 170, 'name' => 'آبادان'],
            ['province_id' => 13, 'county_id' => 170, 'name' => 'اروندکنار'],
            ['province_id' => 13, 'county_id' => 170, 'name' => 'چویبده'],
            ['province_id' => 13, 'county_id' => 171, 'name' => 'آغاجاری'],
            ['province_id' => 13, 'county_id' => 172, 'name' => 'امیدیه'],
            ['province_id' => 13, 'county_id' => 172, 'name' => 'جایزان'],
            ['province_id' => 13, 'county_id' => 173, 'name' => 'آبژدان'],
            ['province_id' => 13, 'county_id' => 173, 'name' => 'قلعه خواجه'],
            ['province_id' => 13, 'county_id' => 174, 'name' => 'آزادی'],
            ['province_id' => 13, 'county_id' => 174, 'name' => 'اندیمشک'],
            ['province_id' => 13, 'county_id' => 174, 'name' => 'بیدروبه'],
            ['province_id' => 13, 'county_id' => 174, 'name' => 'چم گلک'],
            ['province_id' => 13, 'county_id' => 174, 'name' => 'حسینیه'],
            ['province_id' => 13, 'county_id' => 175, 'name' => 'الهایی'],
            ['province_id' => 13, 'county_id' => 175, 'name' => 'اهواز'],
            ['province_id' => 13, 'county_id' => 176, 'name' => 'ایذه'],
            ['province_id' => 13, 'county_id' => 176, 'name' => 'دهدز'],
            ['province_id' => 13, 'county_id' => 177, 'name' => 'باغ ملک'],
            ['province_id' => 13, 'county_id' => 177, 'name' => 'صیدون'],
            ['province_id' => 13, 'county_id' => 177, 'name' => 'قلعه تل'],
            ['province_id' => 13, 'county_id' => 177, 'name' => 'میداود'],
            ['province_id' => 13, 'county_id' => 178, 'name' => 'شیبان'],
            ['province_id' => 13, 'county_id' => 178, 'name' => 'ملاثانی'],
            ['province_id' => 13, 'county_id' => 178, 'name' => 'ویس'],
            ['province_id' => 13, 'county_id' => 179, 'name' => 'بندرامام خمینی'],
            ['province_id' => 13, 'county_id' => 179, 'name' => 'بندرماهشهر'],
            ['province_id' => 13, 'county_id' => 179, 'name' => 'چمران'],
            ['province_id' => 13, 'county_id' => 180, 'name' => 'بهبهان'],
            ['province_id' => 13, 'county_id' => 180, 'name' => 'تشان'],
            ['province_id' => 13, 'county_id' => 180, 'name' => 'سردشت'],
            ['province_id' => 13, 'county_id' => 180, 'name' => 'منصوریه'],
            ['province_id' => 13, 'county_id' => 181, 'name' => 'حمیدیه'],
            ['province_id' => 13, 'county_id' => 182, 'name' => 'خرمشهر'],
            ['province_id' => 13, 'county_id' => 182, 'name' => 'مقاومت'],
            ['province_id' => 13, 'county_id' => 182, 'name' => 'مینوشهر'],
            ['province_id' => 13, 'county_id' => 183, 'name' => 'چغامیش'],
            ['province_id' => 13, 'county_id' => 183, 'name' => 'حمزه'],
            ['province_id' => 13, 'county_id' => 183, 'name' => 'دزفول'],
            ['province_id' => 13, 'county_id' => 183, 'name' => 'سالند'],
            ['province_id' => 13, 'county_id' => 183, 'name' => 'سیاه منصور'],
            ['province_id' => 13, 'county_id' => 183, 'name' => 'شمس آباد'],
            ['province_id' => 13, 'county_id' => 183, 'name' => 'شهر امام'],
            ['province_id' => 13, 'county_id' => 183, 'name' => 'صفی آباد'],
            ['province_id' => 13, 'county_id' => 183, 'name' => 'میانرود'],
            ['province_id' => 13, 'county_id' => 184, 'name' => 'ابوحمیظه'],
            ['province_id' => 13, 'county_id' => 184, 'name' => 'بستان'],
            ['province_id' => 13, 'county_id' => 184, 'name' => 'سوسنگرد'],
            ['province_id' => 13, 'county_id' => 184, 'name' => 'کوت سیدنعیم'],
            ['province_id' => 13, 'county_id' => 185, 'name' => 'رامشیر'],
            ['province_id' => 13, 'county_id' => 185, 'name' => 'مشراگه'],
            ['province_id' => 13, 'county_id' => 186, 'name' => 'رامهرمز'],
            ['province_id' => 13, 'county_id' => 187, 'name' => 'خنافره'],
            ['province_id' => 13, 'county_id' => 187, 'name' => 'دارخوین'],
            ['province_id' => 13, 'county_id' => 187, 'name' => 'شادگان'],
            ['province_id' => 13, 'county_id' => 188, 'name' => 'الوان'],
            ['province_id' => 13, 'county_id' => 188, 'name' => 'حر'],
            ['province_id' => 13, 'county_id' => 188, 'name' => 'شاوور'],
            ['province_id' => 13, 'county_id' => 188, 'name' => 'شوش'],
            ['province_id' => 13, 'county_id' => 188, 'name' => 'فتح المبین'],
            ['province_id' => 13, 'county_id' => 189, 'name' => 'سرداران'],
            ['province_id' => 13, 'county_id' => 189, 'name' => 'شرافت'],
            ['province_id' => 13, 'county_id' => 189, 'name' => 'شوشتر'],
            ['province_id' => 13, 'county_id' => 189, 'name' => 'گوریه'],
            ['province_id' => 13, 'county_id' => 190, 'name' => 'کوت عبداله'],
            ['province_id' => 13, 'county_id' => 191, 'name' => 'ترکالکی'],
            ['province_id' => 13, 'county_id' => 191, 'name' => 'جنت مکان'],
            ['province_id' => 13, 'county_id' => 191, 'name' => 'سماله'],
            ['province_id' => 13, 'county_id' => 191, 'name' => 'صالح شهر'],
            ['province_id' => 13, 'county_id' => 191, 'name' => 'گتوند'],
            ['province_id' => 13, 'county_id' => 192, 'name' => 'لالی'],
            ['province_id' => 13, 'county_id' => 193, 'name' => 'گلگیر'],
            ['province_id' => 13, 'county_id' => 193, 'name' => 'مسجدسلیمان'],
            ['province_id' => 13, 'county_id' => 194, 'name' => 'هفتگل'],
            ['province_id' => 13, 'county_id' => 195, 'name' => 'زهره'],
            ['province_id' => 13, 'county_id' => 195, 'name' => 'هندیجان'],
            ['province_id' => 13, 'county_id' => 196, 'name' => 'رفیع'],
            ['province_id' => 13, 'county_id' => 196, 'name' => 'هویزه'],
            ['province_id' => 14, 'county_id' => 197, 'name' => 'ابهر'],
            ['province_id' => 14, 'county_id' => 197, 'name' => 'صایین قلعه'],
            ['province_id' => 14, 'county_id' => 197, 'name' => 'هیدج'],
            ['province_id' => 14, 'county_id' => 198, 'name' => 'حلب'],
            ['province_id' => 14, 'county_id' => 198, 'name' => 'زرین آباد'],
            ['province_id' => 14, 'county_id' => 199, 'name' => 'زرین رود'],
            ['province_id' => 14, 'county_id' => 199, 'name' => 'سجاس'],
            ['province_id' => 14, 'county_id' => 199, 'name' => 'سهرورد'],
            ['province_id' => 14, 'county_id' => 199, 'name' => 'قیدار'],
            ['province_id' => 14, 'county_id' => 199, 'name' => 'کرسف'],
            ['province_id' => 14, 'county_id' => 199, 'name' => 'گرماب'],
            ['province_id' => 14, 'county_id' => 199, 'name' => 'نوربهار'],
            ['province_id' => 14, 'county_id' => 200, 'name' => 'خرمدره'],
            ['province_id' => 14, 'county_id' => 201, 'name' => 'ارمغانخانه'],
            ['province_id' => 14, 'county_id' => 201, 'name' => 'زنجان'],
            ['province_id' => 14, 'county_id' => 201, 'name' => 'نیک پی'],
            ['province_id' => 14, 'county_id' => 202, 'name' => 'سلطانیه'],
            ['province_id' => 14, 'county_id' => 203, 'name' => 'آب بر'],
            ['province_id' => 14, 'county_id' => 203, 'name' => 'چورزق'],
            ['province_id' => 14, 'county_id' => 204, 'name' => 'دندی'],
            ['province_id' => 14, 'county_id' => 204, 'name' => 'ماه نشان'],
            ['province_id' => 15, 'county_id' => 205, 'name' => 'آرادان'],
            ['province_id' => 15, 'county_id' => 205, 'name' => 'کهن آباد'],
            ['province_id' => 15, 'county_id' => 206, 'name' => 'امیریه'],
            ['province_id' => 15, 'county_id' => 206, 'name' => 'دامغان'],
            ['province_id' => 15, 'county_id' => 206, 'name' => 'دیباج'],
            ['province_id' => 15, 'county_id' => 206, 'name' => 'کلاته'],
            ['province_id' => 15, 'county_id' => 207, 'name' => 'سرخه'],
            ['province_id' => 15, 'county_id' => 208, 'name' => 'سمنان'],
            ['province_id' => 15, 'county_id' => 209, 'name' => 'بسطام'],
            ['province_id' => 15, 'county_id' => 209, 'name' => 'بیارجمند'],
            ['province_id' => 15, 'county_id' => 209, 'name' => 'رودیان'],
            ['province_id' => 15, 'county_id' => 209, 'name' => 'شاهرود'],
            ['province_id' => 15, 'county_id' => 209, 'name' => 'کلاته خیج'],
            ['province_id' => 15, 'county_id' => 209, 'name' => 'مجن'],
            ['province_id' => 15, 'county_id' => 210, 'name' => 'ایوانکی'],
            ['province_id' => 15, 'county_id' => 210, 'name' => 'گرمسار'],
            ['province_id' => 15, 'county_id' => 211, 'name' => 'درجزین'],
            ['province_id' => 15, 'county_id' => 211, 'name' => 'شهمیرزاد'],
            ['province_id' => 15, 'county_id' => 211, 'name' => 'مهدی شهر'],
            ['province_id' => 15, 'county_id' => 212, 'name' => 'میامی'],
            ['province_id' => 16, 'county_id' => 213, 'name' => 'ایرانشهر'],
            ['province_id' => 16, 'county_id' => 213, 'name' => 'بزمان'],
            ['province_id' => 16, 'county_id' => 213, 'name' => 'بمپور'],
            ['province_id' => 16, 'county_id' => 213, 'name' => 'محمدان'],
            ['province_id' => 16, 'county_id' => 214, 'name' => 'چابهار'],
            ['province_id' => 16, 'county_id' => 214, 'name' => 'نگور'],
            ['province_id' => 16, 'county_id' => 215, 'name' => 'خاش'],
            ['province_id' => 16, 'county_id' => 215, 'name' => 'نوک آباد'],
            ['province_id' => 16, 'county_id' => 216, 'name' => 'گلمورتی'],
            ['province_id' => 16, 'county_id' => 217, 'name' => 'بنجار'],
            ['province_id' => 16, 'county_id' => 217, 'name' => 'زابل'],
            ['province_id' => 16, 'county_id' => 218, 'name' => 'زاهدان'],
            ['province_id' => 16, 'county_id' => 218, 'name' => 'نصرت آباد'],
            ['province_id' => 16, 'county_id' => 219, 'name' => 'زهک'],
            ['province_id' => 16, 'county_id' => 220, 'name' => 'جالق'],
            ['province_id' => 16, 'county_id' => 220, 'name' => 'سراوان'],
            ['province_id' => 16, 'county_id' => 220, 'name' => 'سیرکان'],
            ['province_id' => 16, 'county_id' => 220, 'name' => 'گشت'],
            ['province_id' => 16, 'county_id' => 220, 'name' => 'محمدی'],
            ['province_id' => 16, 'county_id' => 221, 'name' => 'پیشین'],
            ['province_id' => 16, 'county_id' => 221, 'name' => 'راسک'],
            ['province_id' => 16, 'county_id' => 221, 'name' => 'سرباز'],
            ['province_id' => 16, 'county_id' => 222, 'name' => 'سوران'],
            ['province_id' => 16, 'county_id' => 222, 'name' => 'هیدوچ'],
            ['province_id' => 16, 'county_id' => 223, 'name' => 'فنوج'],
            ['province_id' => 16, 'county_id' => 224, 'name' => 'قصرقند'],
            ['province_id' => 16, 'county_id' => 225, 'name' => 'زرآباد'],
            ['province_id' => 16, 'county_id' => 225, 'name' => 'کنارک'],
            ['province_id' => 16, 'county_id' => 226, 'name' => 'مهرستان'],
            ['province_id' => 16, 'county_id' => 227, 'name' => 'میرجاوه'],
            ['province_id' => 16, 'county_id' => 228, 'name' => 'اسپکه'],
            ['province_id' => 16, 'county_id' => 228, 'name' => 'بنت'],
            ['province_id' => 16, 'county_id' => 228, 'name' => 'نیک شهر'],
            ['province_id' => 16, 'county_id' => 229, 'name' => 'ادیمی'],
            ['province_id' => 16, 'county_id' => 230, 'name' => 'شهرک علی اکبر'],
            ['province_id' => 16, 'county_id' => 230, 'name' => 'محمدآباد'],
            ['province_id' => 16, 'county_id' => 231, 'name' => 'دوست محمد'],
            ['province_id' => 17, 'county_id' => 232, 'name' => 'آباده'],
            ['province_id' => 17, 'county_id' => 232, 'name' => 'ایزدخواست'],
            ['province_id' => 17, 'county_id' => 232, 'name' => 'بهمن'],
            ['province_id' => 17, 'county_id' => 232, 'name' => 'سورمق'],
            ['province_id' => 17, 'county_id' => 232, 'name' => 'صغاد'],
            ['province_id' => 17, 'county_id' => 233, 'name' => 'ارسنجان'],
            ['province_id' => 17, 'county_id' => 234, 'name' => 'استهبان'],
            ['province_id' => 17, 'county_id' => 234, 'name' => 'ایج'],
            ['province_id' => 17, 'county_id' => 234, 'name' => 'رونیز'],
            ['province_id' => 17, 'county_id' => 235, 'name' => 'اقلید'],
            ['province_id' => 17, 'county_id' => 235, 'name' => 'حسن اباد'],
            ['province_id' => 17, 'county_id' => 235, 'name' => 'دژکرد'],
            ['province_id' => 17, 'county_id' => 235, 'name' => 'سده'],
            ['province_id' => 17, 'county_id' => 236, 'name' => 'بوانات'],
            ['province_id' => 17, 'county_id' => 236, 'name' => 'حسامی'],
            ['province_id' => 17, 'county_id' => 236, 'name' => 'کره ای'],
            ['province_id' => 17, 'county_id' => 236, 'name' => 'مزایجان'],
            ['province_id' => 17, 'county_id' => 237, 'name' => 'سعادت شهر'],
            ['province_id' => 17, 'county_id' => 237, 'name' => 'مادرسلیمان'],
            ['province_id' => 17, 'county_id' => 238, 'name' => 'باب انار'],
            ['province_id' => 17, 'county_id' => 238, 'name' => 'جهرم'],
            ['province_id' => 17, 'county_id' => 238, 'name' => 'خاوران'],
            ['province_id' => 17, 'county_id' => 238, 'name' => 'دوزه'],
            ['province_id' => 17, 'county_id' => 238, 'name' => 'قطب آباد'],
            ['province_id' => 17, 'county_id' => 239, 'name' => 'خرامه'],
            ['province_id' => 17, 'county_id' => 239, 'name' => 'سلطان شهر'],
            ['province_id' => 17, 'county_id' => 240, 'name' => 'صفاشهر'],
            ['province_id' => 17, 'county_id' => 240, 'name' => 'قادراباد'],
            ['province_id' => 17, 'county_id' => 241, 'name' => 'خنج'],
            ['province_id' => 17, 'county_id' => 242, 'name' => 'جنت شهر'],
            ['province_id' => 17, 'county_id' => 242, 'name' => 'داراب'],
            ['province_id' => 17, 'county_id' => 242, 'name' => 'دوبرجی'],
            ['province_id' => 17, 'county_id' => 242, 'name' => 'فدامی'],
            ['province_id' => 17, 'county_id' => 243, 'name' => 'کوپن'],
            ['province_id' => 17, 'county_id' => 243, 'name' => 'مصیری'],
            ['province_id' => 17, 'county_id' => 244, 'name' => 'حاجی آباد'],
            ['province_id' => 17, 'county_id' => 244, 'name' => 'دبیران'],
            ['province_id' => 17, 'county_id' => 244, 'name' => 'شهرپیر'],
            ['province_id' => 17, 'county_id' => 245, 'name' => 'اردکان'],
            ['province_id' => 17, 'county_id' => 245, 'name' => 'بیضا'],
            ['province_id' => 17, 'county_id' => 245, 'name' => 'هماشهر'],
            ['province_id' => 17, 'county_id' => 246, 'name' => 'سروستان'],
            ['province_id' => 17, 'county_id' => 246, 'name' => 'کوهنجان'],
            ['province_id' => 17, 'county_id' => 247, 'name' => 'خانه زنیان'],
            ['province_id' => 17, 'county_id' => 247, 'name' => 'داریان'],
            ['province_id' => 17, 'county_id' => 247, 'name' => 'زرقان'],
            ['province_id' => 17, 'county_id' => 247, 'name' => 'شهرصدرا'],
            ['province_id' => 17, 'county_id' => 247, 'name' => 'شیراز'],
            ['province_id' => 17, 'county_id' => 247, 'name' => 'لپویی'],
            ['province_id' => 17, 'county_id' => 248, 'name' => 'دهرم'],
            ['province_id' => 17, 'county_id' => 248, 'name' => 'فراشبند'],
            ['province_id' => 17, 'county_id' => 248, 'name' => 'نوجین'],
            ['province_id' => 17, 'county_id' => 249, 'name' => 'زاهدشهر'],
            ['province_id' => 17, 'county_id' => 249, 'name' => 'ششده'],
            ['province_id' => 17, 'county_id' => 249, 'name' => 'فسا'],
            ['province_id' => 17, 'county_id' => 249, 'name' => 'قره بلاغ'],
            ['province_id' => 17, 'county_id' => 249, 'name' => 'میانشهر'],
            ['province_id' => 17, 'county_id' => 249, 'name' => 'نوبندگان'],
            ['province_id' => 17, 'county_id' => 250, 'name' => 'فیروزآباد'],
            ['province_id' => 17, 'county_id' => 250, 'name' => 'میمند'],
            ['province_id' => 17, 'county_id' => 251, 'name' => 'افزر'],
            ['province_id' => 17, 'county_id' => 251, 'name' => 'امام شهر'],
            ['province_id' => 17, 'county_id' => 251, 'name' => 'قیر'],
            ['province_id' => 17, 'county_id' => 251, 'name' => 'کارزین (فتح‌آباد)'],
            ['province_id' => 17, 'county_id' => 251, 'name' => 'مبارک آباد دیز'],
            ['province_id' => 17, 'county_id' => 252, 'name' => 'بالاده'],
            ['province_id' => 17, 'county_id' => 252, 'name' => 'خشت'],
            ['province_id' => 17, 'county_id' => 252, 'name' => 'قایمیه'],
            ['province_id' => 17, 'county_id' => 252, 'name' => 'کازرون'],
            ['province_id' => 17, 'county_id' => 252, 'name' => 'کنارتخته'],
            ['province_id' => 17, 'county_id' => 252, 'name' => 'نودان'],
            ['province_id' => 17, 'county_id' => 253, 'name' => 'کوار'],
            ['province_id' => 17, 'county_id' => 254, 'name' => 'گراش'],
            ['province_id' => 17, 'county_id' => 255, 'name' => 'اوز'],
            ['province_id' => 17, 'county_id' => 255, 'name' => 'بنارویه'],
            ['province_id' => 17, 'county_id' => 255, 'name' => 'بیرم'],
            ['province_id' => 17, 'county_id' => 255, 'name' => 'جویم'],
            ['province_id' => 17, 'county_id' => 255, 'name' => 'خور'],
            ['province_id' => 17, 'county_id' => 255, 'name' => 'عمادده'],
            ['province_id' => 17, 'county_id' => 255, 'name' => 'لار'],
            ['province_id' => 17, 'county_id' => 255, 'name' => 'لطیفی'],
            ['province_id' => 17, 'county_id' => 256, 'name' => 'اشکنان'],
            ['province_id' => 17, 'county_id' => 256, 'name' => 'اهل'],
            ['province_id' => 17, 'county_id' => 256, 'name' => 'علامرودشت'],
            ['province_id' => 17, 'county_id' => 256, 'name' => 'لامرد'],
            ['province_id' => 17, 'county_id' => 257, 'name' => 'خانیمن'],
            ['province_id' => 17, 'county_id' => 257, 'name' => 'رامجرد'],
            ['province_id' => 17, 'county_id' => 257, 'name' => 'سیدان'],
            ['province_id' => 17, 'county_id' => 257, 'name' => 'کامفیروز'],
            ['province_id' => 17, 'county_id' => 257, 'name' => 'مرودشت'],
            ['province_id' => 17, 'county_id' => 258, 'name' => 'بابامنیر'],
            ['province_id' => 17, 'county_id' => 258, 'name' => 'خومه زار'],
            ['province_id' => 17, 'county_id' => 258, 'name' => 'نورآباد'],
            ['province_id' => 17, 'county_id' => 259, 'name' => 'اسیر'],
            ['province_id' => 17, 'county_id' => 259, 'name' => 'خوزی'],
            ['province_id' => 17, 'county_id' => 259, 'name' => 'گله دار'],
            ['province_id' => 17, 'county_id' => 259, 'name' => 'مهر'],
            ['province_id' => 17, 'county_id' => 259, 'name' => 'وراوی'],
            ['province_id' => 17, 'county_id' => 260, 'name' => 'آباده طشک'],
            ['province_id' => 17, 'county_id' => 260, 'name' => 'قطرویه'],
            ['province_id' => 17, 'county_id' => 260, 'name' => 'مشکان'],
            ['province_id' => 17, 'county_id' => 260, 'name' => 'نی ریز'],
            ['province_id' => 18, 'county_id' => 261, 'name' => 'آبیک'],
            ['province_id' => 18, 'county_id' => 261, 'name' => 'خاکعلی'],
            ['province_id' => 18, 'county_id' => 262, 'name' => 'آبگرم'],
            ['province_id' => 18, 'county_id' => 262, 'name' => 'آوج'],
            ['province_id' => 18, 'county_id' => 263, 'name' => 'الوند'],
            ['province_id' => 18, 'county_id' => 263, 'name' => 'بیدستان'],
            ['province_id' => 18, 'county_id' => 263, 'name' => 'شریفیه'],
            ['province_id' => 18, 'county_id' => 263, 'name' => 'محمدیه'],
            ['province_id' => 18, 'county_id' => 264, 'name' => 'ارداق'],
            ['province_id' => 18, 'county_id' => 264, 'name' => 'بویین زهرا'],
            ['province_id' => 18, 'county_id' => 264, 'name' => 'دانسفهان'],
            ['province_id' => 18, 'county_id' => 264, 'name' => 'سگزآباد'],
            ['province_id' => 18, 'county_id' => 264, 'name' => 'شال'],
            ['province_id' => 18, 'county_id' => 265, 'name' => 'اسفرورین'],
            ['province_id' => 18, 'county_id' => 265, 'name' => 'تاکستان'],
            ['province_id' => 18, 'county_id' => 265, 'name' => 'خرمدشت'],
            ['province_id' => 18, 'county_id' => 265, 'name' => 'ضیاڈآباد'],
            ['province_id' => 18, 'county_id' => 265, 'name' => 'نرجه'],
            ['province_id' => 18, 'county_id' => 266, 'name' => 'اقبالیه'],
            ['province_id' => 18, 'county_id' => 266, 'name' => 'رازمیان'],
            ['province_id' => 18, 'county_id' => 266, 'name' => 'سیردان'],
            ['province_id' => 18, 'county_id' => 266, 'name' => 'قزوین'],
            ['province_id' => 18, 'county_id' => 266, 'name' => 'کوهین'],
            ['province_id' => 18, 'county_id' => 266, 'name' => 'محمودآبادنمونه'],
            ['province_id' => 18, 'county_id' => 266, 'name' => 'معلم کلایه'],
            ['province_id' => 19, 'county_id' => 267, 'name' => 'جعفریه'],
            ['province_id' => 19, 'county_id' => 267, 'name' => 'دستجرد'],
            ['province_id' => 19, 'county_id' => 267, 'name' => 'سلفچگان'],
            ['province_id' => 19, 'county_id' => 267, 'name' => 'قم'],
            ['province_id' => 19, 'county_id' => 267, 'name' => 'قنوات'],
            ['province_id' => 19, 'county_id' => 267, 'name' => 'کهک'],
            ['province_id' => 20, 'county_id' => 268, 'name' => 'آرمرده'],
            ['province_id' => 20, 'county_id' => 268, 'name' => 'بانه'],
            ['province_id' => 20, 'county_id' => 268, 'name' => 'بویین سفلی'],
            ['province_id' => 20, 'county_id' => 268, 'name' => 'کانی سور'],
            ['province_id' => 20, 'county_id' => 269, 'name' => 'بابارشانی'],
            ['province_id' => 20, 'county_id' => 269, 'name' => 'بیجار'],
            ['province_id' => 20, 'county_id' => 269, 'name' => 'پیرتاج'],
            ['province_id' => 20, 'county_id' => 269, 'name' => 'توپ آغاج'],
            ['province_id' => 20, 'county_id' => 269, 'name' => 'یاسوکند'],
            ['province_id' => 20, 'county_id' => 270, 'name' => 'بلبان آباد'],
            ['province_id' => 20, 'county_id' => 270, 'name' => 'دهگلان'],
            ['province_id' => 20, 'county_id' => 271, 'name' => 'دیواندره'],
            ['province_id' => 20, 'county_id' => 271, 'name' => 'زرینه'],
            ['province_id' => 20, 'county_id' => 272, 'name' => 'اورامان تخت'],
            ['province_id' => 20, 'county_id' => 272, 'name' => 'سروآباد'],
            ['province_id' => 20, 'county_id' => 273, 'name' => 'سقز'],
            ['province_id' => 20, 'county_id' => 273, 'name' => 'صاحب'],
            ['province_id' => 20, 'county_id' => 274, 'name' => 'سنندج'],
            ['province_id' => 20, 'county_id' => 274, 'name' => 'شویشه'],
            ['province_id' => 20, 'county_id' => 275, 'name' => 'دزج'],
            ['province_id' => 20, 'county_id' => 275, 'name' => 'دلبران'],
            ['province_id' => 20, 'county_id' => 275, 'name' => 'سریش آباد'],
            ['province_id' => 20, 'county_id' => 275, 'name' => 'قروه'],
            ['province_id' => 20, 'county_id' => 276, 'name' => 'کامیاران'],
            ['province_id' => 20, 'county_id' => 276, 'name' => 'موچش'],
            ['province_id' => 20, 'county_id' => 277, 'name' => 'برده رشه'],
            ['province_id' => 20, 'county_id' => 277, 'name' => 'چناره'],
            ['province_id' => 20, 'county_id' => 277, 'name' => 'کانی دینار'],
            ['province_id' => 20, 'county_id' => 277, 'name' => 'مریوان'],
            ['province_id' => 21, 'county_id' => 278, 'name' => 'ارزوییه'],
            ['province_id' => 21, 'county_id' => 279, 'name' => 'امین شهر'],
            ['province_id' => 21, 'county_id' => 279, 'name' => 'انار'],
            ['province_id' => 21, 'county_id' => 280, 'name' => 'بافت'],
            ['province_id' => 21, 'county_id' => 280, 'name' => 'بزنجان'],
            ['province_id' => 21, 'county_id' => 281, 'name' => 'بردسیر'],
            ['province_id' => 21, 'county_id' => 281, 'name' => 'دشتکار'],
            ['province_id' => 21, 'county_id' => 281, 'name' => 'گلزار'],
            ['province_id' => 21, 'county_id' => 281, 'name' => 'لاله زار'],
            ['province_id' => 21, 'county_id' => 281, 'name' => 'نگار'],
            ['province_id' => 21, 'county_id' => 282, 'name' => 'بروات'],
            ['province_id' => 21, 'county_id' => 282, 'name' => 'بم'],
            ['province_id' => 21, 'county_id' => 283, 'name' => 'بلوک'],
            ['province_id' => 21, 'county_id' => 283, 'name' => 'جبالبارز'],
            ['province_id' => 21, 'county_id' => 283, 'name' => 'جیرفت'],
            ['province_id' => 21, 'county_id' => 283, 'name' => 'درب بهشت'],
            ['province_id' => 21, 'county_id' => 284, 'name' => 'رابر'],
            ['province_id' => 21, 'county_id' => 284, 'name' => 'هنزا'],
            ['province_id' => 21, 'county_id' => 285, 'name' => 'راور'],
            ['province_id' => 21, 'county_id' => 285, 'name' => 'هجدک'],
            ['province_id' => 21, 'county_id' => 286, 'name' => 'بهرمان'],
            ['province_id' => 21, 'county_id' => 286, 'name' => 'رفسنجان'],
            ['province_id' => 21, 'county_id' => 286, 'name' => 'صفاییه'],
            ['province_id' => 21, 'county_id' => 286, 'name' => 'کشکوییه'],
            ['province_id' => 21, 'county_id' => 286, 'name' => 'مس سرچشمه'],
            ['province_id' => 21, 'county_id' => 287, 'name' => 'رودبار'],
            ['province_id' => 21, 'county_id' => 287, 'name' => 'زهکلوت'],
            ['province_id' => 21, 'county_id' => 288, 'name' => 'گنبکی'],
            ['province_id' => 21, 'county_id' => 288, 'name' => 'محمدآباد'],
            ['province_id' => 21, 'county_id' => 289, 'name' => 'خانوک'],
            ['province_id' => 21, 'county_id' => 289, 'name' => 'ریحان'],
            ['province_id' => 21, 'county_id' => 289, 'name' => 'زرند'],
            ['province_id' => 21, 'county_id' => 289, 'name' => 'یزدان شهر'],
            ['province_id' => 21, 'county_id' => 290, 'name' => 'بلورد'],
            ['province_id' => 21, 'county_id' => 290, 'name' => 'پاریز'],
            ['province_id' => 21, 'county_id' => 290, 'name' => 'خواجو شهر'],
            ['province_id' => 21, 'county_id' => 290, 'name' => 'زیدآباد'],
            ['province_id' => 21, 'county_id' => 290, 'name' => 'سیرجان'],
            ['province_id' => 21, 'county_id' => 290, 'name' => 'نجف شهر'],
            ['province_id' => 21, 'county_id' => 290, 'name' => 'هماشهر'],
            ['province_id' => 21, 'county_id' => 291, 'name' => 'جوزم'],
            ['province_id' => 21, 'county_id' => 291, 'name' => 'خاتون اباد'],
            ['province_id' => 21, 'county_id' => 291, 'name' => 'خورسند'],
            ['province_id' => 21, 'county_id' => 291, 'name' => 'دهج'],
            ['province_id' => 21, 'county_id' => 291, 'name' => 'شهربابک'],
            ['province_id' => 21, 'county_id' => 292, 'name' => 'دوساری'],
            ['province_id' => 21, 'county_id' => 292, 'name' => 'عنبرآباد'],
            ['province_id' => 21, 'county_id' => 292, 'name' => 'مردهک'],
            ['province_id' => 21, 'county_id' => 293, 'name' => 'فاریاب'],
            ['province_id' => 21, 'county_id' => 294, 'name' => 'فهرج'],
            ['province_id' => 21, 'county_id' => 295, 'name' => 'قلعه گنج'],
            ['province_id' => 21, 'county_id' => 296, 'name' => 'اختیارآباد'],
            ['province_id' => 21, 'county_id' => 296, 'name' => 'اندوهجرد'],
            ['province_id' => 21, 'county_id' => 296, 'name' => 'باغین'],
            ['province_id' => 21, 'county_id' => 296, 'name' => 'جوپار'],
            ['province_id' => 21, 'county_id' => 296, 'name' => 'چترود'],
            ['province_id' => 21, 'county_id' => 296, 'name' => 'راین'],
            ['province_id' => 21, 'county_id' => 296, 'name' => 'زنگی آباد'],
            ['province_id' => 21, 'county_id' => 296, 'name' => 'شهداد'],
            ['province_id' => 21, 'county_id' => 296, 'name' => 'کاظم آباد'],
            ['province_id' => 21, 'county_id' => 296, 'name' => 'کرمان'],
            ['province_id' => 21, 'county_id' => 296, 'name' => 'گلباف'],
            ['province_id' => 21, 'county_id' => 296, 'name' => 'ماهان'],
            ['province_id' => 21, 'county_id' => 296, 'name' => 'محی آباد'],
            ['province_id' => 21, 'county_id' => 297, 'name' => 'کوهبنان'],
            ['province_id' => 21, 'county_id' => 297, 'name' => 'کیانشهر'],
            ['province_id' => 21, 'county_id' => 298, 'name' => 'کهنوج'],
            ['province_id' => 21, 'county_id' => 299, 'name' => 'منوجان'],
            ['province_id' => 21, 'county_id' => 299, 'name' => 'نودژ'],
            ['province_id' => 21, 'county_id' => 300, 'name' => 'نرماشیر'],
            ['province_id' => 21, 'county_id' => 300, 'name' => 'نظام شهر'],
            ['province_id' => 22, 'county_id' => 301, 'name' => 'اسلام آبادغرب'],
            ['province_id' => 22, 'county_id' => 301, 'name' => 'حمیل'],
            ['province_id' => 22, 'county_id' => 302, 'name' => 'بانوره'],
            ['province_id' => 22, 'county_id' => 302, 'name' => 'باینگان'],
            ['province_id' => 22, 'county_id' => 302, 'name' => 'پاوه'],
            ['province_id' => 22, 'county_id' => 302, 'name' => 'نودشه'],
            ['province_id' => 22, 'county_id' => 302, 'name' => 'نوسود'],
            ['province_id' => 22, 'county_id' => 303, 'name' => 'ازگله'],
            ['province_id' => 22, 'county_id' => 303, 'name' => 'تازه آباد'],
            ['province_id' => 22, 'county_id' => 304, 'name' => 'جوانرود'],
            ['province_id' => 22, 'county_id' => 305, 'name' => 'ریجاب'],
            ['province_id' => 22, 'county_id' => 305, 'name' => 'کرند'],
            ['province_id' => 22, 'county_id' => 305, 'name' => 'گهواره'],
            ['province_id' => 22, 'county_id' => 306, 'name' => 'روانسر'],
            ['province_id' => 22, 'county_id' => 306, 'name' => 'شاهو'],
            ['province_id' => 22, 'county_id' => 307, 'name' => 'سرپل ذهاب'],
            ['province_id' => 22, 'county_id' => 308, 'name' => 'سطر'],
            ['province_id' => 22, 'county_id' => 308, 'name' => 'سنقر'],
            ['province_id' => 22, 'county_id' => 309, 'name' => 'صحنه'],
            ['province_id' => 22, 'county_id' => 309, 'name' => 'میان راهان'],
            ['province_id' => 22, 'county_id' => 310, 'name' => 'سومار'],
            ['province_id' => 22, 'county_id' => 310, 'name' => 'قصرشیرین'],
            ['province_id' => 22, 'county_id' => 311, 'name' => 'رباط'],
            ['province_id' => 22, 'county_id' => 311, 'name' => 'کرمانشاه'],
            ['province_id' => 22, 'county_id' => 311, 'name' => 'کوزران'],
            ['province_id' => 22, 'county_id' => 311, 'name' => 'هلشی'],
            ['province_id' => 22, 'county_id' => 312, 'name' => 'کنگاور'],
            ['province_id' => 22, 'county_id' => 312, 'name' => 'گودین'],
            ['province_id' => 22, 'county_id' => 313, 'name' => 'سرمست'],
            ['province_id' => 22, 'county_id' => 313, 'name' => 'گیلانغرب'],
            ['province_id' => 22, 'county_id' => 314, 'name' => 'بیستون'],
            ['province_id' => 22, 'county_id' => 314, 'name' => 'هرسین'],
            ['province_id' => 23, 'county_id' => 315, 'name' => 'باشت'],
            ['province_id' => 23, 'county_id' => 316, 'name' => 'چیتاب'],
            ['province_id' => 23, 'county_id' => 316, 'name' => 'گراب سفلی'],
            ['province_id' => 23, 'county_id' => 316, 'name' => 'مادوان'],
            ['province_id' => 23, 'county_id' => 316, 'name' => 'مارگون'],
            ['province_id' => 23, 'county_id' => 316, 'name' => 'یاسوج'],
            ['province_id' => 23, 'county_id' => 317, 'name' => 'لیکک'],
            ['province_id' => 23, 'county_id' => 318, 'name' => 'چرام'],
            ['province_id' => 23, 'county_id' => 318, 'name' => 'سرفاریاب'],
            ['province_id' => 23, 'county_id' => 319, 'name' => 'پاتاوه'],
            ['province_id' => 23, 'county_id' => 319, 'name' => 'سی سخت'],
            ['province_id' => 23, 'county_id' => 320, 'name' => 'دهدشت'],
            ['province_id' => 23, 'county_id' => 320, 'name' => 'دیشموک'],
            ['province_id' => 23, 'county_id' => 320, 'name' => 'سوق'],
            ['province_id' => 23, 'county_id' => 320, 'name' => 'قلعه رییسی'],
            ['province_id' => 23, 'county_id' => 321, 'name' => 'دوگنبدان'],
            ['province_id' => 23, 'county_id' => 322, 'name' => 'لنده'],
            ['province_id' => 24, 'county_id' => 323, 'name' => 'آزادشهر'],
            ['province_id' => 24, 'county_id' => 323, 'name' => 'نگین شهر'],
            ['province_id' => 24, 'county_id' => 323, 'name' => 'نوده خاندوز'],
            ['province_id' => 24, 'county_id' => 324, 'name' => 'آق قلا'],
            ['province_id' => 24, 'county_id' => 324, 'name' => 'انبارآلوم'],
            ['province_id' => 24, 'county_id' => 325, 'name' => 'بندرگز'],
            ['province_id' => 24, 'county_id' => 325, 'name' => 'نوکنده'],
            ['province_id' => 24, 'county_id' => 326, 'name' => 'بندرترکمن'],
            ['province_id' => 24, 'county_id' => 327, 'name' => 'تاتارعلیا'],
            ['province_id' => 24, 'county_id' => 327, 'name' => 'خان ببین'],
            ['province_id' => 24, 'county_id' => 327, 'name' => 'دلند'],
            ['province_id' => 24, 'county_id' => 327, 'name' => 'رامیان'],
            ['province_id' => 24, 'county_id' => 328, 'name' => 'سنگدوین'],
            ['province_id' => 24, 'county_id' => 328, 'name' => 'علی اباد'],
            ['province_id' => 24, 'county_id' => 328, 'name' => 'فاضل آباد'],
            ['province_id' => 24, 'county_id' => 328, 'name' => 'مزرعه'],
            ['province_id' => 24, 'county_id' => 329, 'name' => 'کردکوی'],
            ['province_id' => 24, 'county_id' => 330, 'name' => 'فراغی'],
            ['province_id' => 24, 'county_id' => 330, 'name' => 'کلاله'],
            ['province_id' => 24, 'county_id' => 331, 'name' => 'گالیکش'],
            ['province_id' => 24, 'county_id' => 332, 'name' => 'جلین'],
            ['province_id' => 24, 'county_id' => 332, 'name' => 'سرخنکلاته'],
            ['province_id' => 24, 'county_id' => 332, 'name' => 'گرگان'],
            ['province_id' => 24, 'county_id' => 333, 'name' => 'سیمین شهر'],
            ['province_id' => 24, 'county_id' => 333, 'name' => 'گمیش تپه'],
            ['province_id' => 24, 'county_id' => 334, 'name' => 'اینچه برون'],
            ['province_id' => 24, 'county_id' => 334, 'name' => 'گنبدکاووس'],
            ['province_id' => 24, 'county_id' => 335, 'name' => 'مراوه'],
            ['province_id' => 24, 'county_id' => 336, 'name' => 'مینودشت'],
            ['province_id' => 25, 'county_id' => 337, 'name' => 'آستارا'],
            ['province_id' => 25, 'county_id' => 337, 'name' => 'لوندویل'],
            ['province_id' => 25, 'county_id' => 338, 'name' => 'آستانه اشرفیه'],
            ['province_id' => 25, 'county_id' => 338, 'name' => 'کیاشهر'],
            ['province_id' => 25, 'county_id' => 339, 'name' => 'املش'],
            ['province_id' => 25, 'county_id' => 339, 'name' => 'رانکوه'],
            ['province_id' => 25, 'county_id' => 340, 'name' => 'بندرانزلی'],
            ['province_id' => 25, 'county_id' => 341, 'name' => 'خشکبیجار'],
            ['province_id' => 25, 'county_id' => 341, 'name' => 'خمام'],
            ['province_id' => 25, 'county_id' => 341, 'name' => 'رشت'],
            ['province_id' => 25, 'county_id' => 341, 'name' => 'سنگر'],
            ['province_id' => 25, 'county_id' => 341, 'name' => 'کوچصفهان'],
            ['province_id' => 25, 'county_id' => 341, 'name' => 'لشت نشاء'],
            ['province_id' => 25, 'county_id' => 341, 'name' => 'لولمان'],
            ['province_id' => 25, 'county_id' => 342, 'name' => 'پره سر'],
            ['province_id' => 25, 'county_id' => 342, 'name' => 'رضوانشهر'],
            ['province_id' => 25, 'county_id' => 343, 'name' => 'بره سر'],
            ['province_id' => 25, 'county_id' => 343, 'name' => 'توتکابن'],
            ['province_id' => 25, 'county_id' => 343, 'name' => 'جیرنده'],
            ['province_id' => 25, 'county_id' => 343, 'name' => 'رستم آباد'],
            ['province_id' => 25, 'county_id' => 343, 'name' => 'رودبار'],
            ['province_id' => 25, 'county_id' => 343, 'name' => 'لوشان'],
            ['province_id' => 25, 'county_id' => 343, 'name' => 'منجیل'],
            ['province_id' => 25, 'county_id' => 344, 'name' => 'چابکسر'],
            ['province_id' => 25, 'county_id' => 344, 'name' => 'رحیم آباد'],
            ['province_id' => 25, 'county_id' => 344, 'name' => 'رودسر'],
            ['province_id' => 25, 'county_id' => 344, 'name' => 'کلاچای'],
            ['province_id' => 25, 'county_id' => 344, 'name' => 'واجارگاه'],
            ['province_id' => 25, 'county_id' => 345, 'name' => 'دیلمان'],
            ['province_id' => 25, 'county_id' => 345, 'name' => 'سیاهکل'],
            ['province_id' => 25, 'county_id' => 346, 'name' => 'احمدسرگوراب'],
            ['province_id' => 25, 'county_id' => 346, 'name' => 'شفت'],
            ['province_id' => 25, 'county_id' => 347, 'name' => 'صومعه سرا'],
            ['province_id' => 25, 'county_id' => 347, 'name' => 'گوراب زرمیخ'],
            ['province_id' => 25, 'county_id' => 347, 'name' => 'مرجقل'],
            ['province_id' => 25, 'county_id' => 348, 'name' => 'اسالم'],
            ['province_id' => 25, 'county_id' => 348, 'name' => 'چوبر'],
            ['province_id' => 25, 'county_id' => 348, 'name' => 'حویق'],
            ['province_id' => 25, 'county_id' => 348, 'name' => 'لیسار'],
            ['province_id' => 25, 'county_id' => 348, 'name' => 'هشتپر (تالش)'],
            ['province_id' => 25, 'county_id' => 349, 'name' => 'فومن'],
            ['province_id' => 25, 'county_id' => 349, 'name' => 'ماسوله'],
            ['province_id' => 25, 'county_id' => 349, 'name' => 'ماکلوان'],
            ['province_id' => 25, 'county_id' => 350, 'name' => 'رودبنه'],
            ['province_id' => 25, 'county_id' => 350, 'name' => 'لاهیجان'],
            ['province_id' => 25, 'county_id' => 351, 'name' => 'اطاقور'],
            ['province_id' => 25, 'county_id' => 351, 'name' => 'چاف و چمخاله'],
            ['province_id' => 25, 'county_id' => 351, 'name' => 'شلمان'],
            ['province_id' => 25, 'county_id' => 351, 'name' => 'کومله'],
            ['province_id' => 25, 'county_id' => 351, 'name' => 'لنگرود'],
            ['province_id' => 25, 'county_id' => 352, 'name' => 'بازار جمعه'],
            ['province_id' => 25, 'county_id' => 352, 'name' => 'ماسال'],
            ['province_id' => 26, 'county_id' => 353, 'name' => 'ازنا'],
            ['province_id' => 26, 'county_id' => 353, 'name' => 'مومن آباد'],
            ['province_id' => 26, 'county_id' => 354, 'name' => 'الیگودرز'],
            ['province_id' => 26, 'county_id' => 354, 'name' => 'شول آباد'],
            ['province_id' => 26, 'county_id' => 355, 'name' => 'اشترینان'],
            ['province_id' => 26, 'county_id' => 355, 'name' => 'بروجرد'],
            ['province_id' => 26, 'county_id' => 356, 'name' => 'پلدختر'],
            ['province_id' => 26, 'county_id' => 356, 'name' => 'معمولان'],
            ['province_id' => 26, 'county_id' => 357, 'name' => 'بیران شهر'],
            ['province_id' => 26, 'county_id' => 357, 'name' => 'خرم آباد'],
            ['province_id' => 26, 'county_id' => 357, 'name' => 'زاغه'],
            ['province_id' => 26, 'county_id' => 357, 'name' => 'سپیددشت'],
            ['province_id' => 26, 'county_id' => 358, 'name' => 'نورآباد'],
            ['province_id' => 26, 'county_id' => 358, 'name' => 'هفت چشمه'],
            ['province_id' => 26, 'county_id' => 359, 'name' => 'چالانچولان'],
            ['province_id' => 26, 'county_id' => 359, 'name' => 'دورود'],
            ['province_id' => 26, 'county_id' => 360, 'name' => 'سراب دوره'],
            ['province_id' => 26, 'county_id' => 360, 'name' => 'ویسیان'],
            ['province_id' => 26, 'county_id' => 361, 'name' => 'چقابل'],
            ['province_id' => 26, 'county_id' => 362, 'name' => 'الشتر'],
            ['province_id' => 26, 'county_id' => 362, 'name' => 'فیروزآباد'],
            ['province_id' => 26, 'county_id' => 363, 'name' => 'درب گنبد'],
            ['province_id' => 26, 'county_id' => 363, 'name' => 'کوهدشت'],
            ['province_id' => 26, 'county_id' => 363, 'name' => 'کوهنانی'],
            ['province_id' => 26, 'county_id' => 363, 'name' => 'گراب'],
            ['province_id' => 27, 'county_id' => 364, 'name' => 'آمل'],
            ['province_id' => 27, 'county_id' => 364, 'name' => 'امامزاده عبدالله'],
            ['province_id' => 27, 'county_id' => 364, 'name' => 'دابودشت'],
            ['province_id' => 27, 'county_id' => 364, 'name' => 'رینه'],
            ['province_id' => 27, 'county_id' => 364, 'name' => 'گزنک'],
            ['province_id' => 27, 'county_id' => 365, 'name' => 'امیرکلا'],
            ['province_id' => 27, 'county_id' => 365, 'name' => 'بابل'],
            ['province_id' => 27, 'county_id' => 365, 'name' => 'خوش رودپی'],
            ['province_id' => 27, 'county_id' => 365, 'name' => 'زرگرمحله'],
            ['province_id' => 27, 'county_id' => 365, 'name' => 'گتاب'],
            ['province_id' => 27, 'county_id' => 365, 'name' => 'گلوگاه'],
            ['province_id' => 27, 'county_id' => 365, 'name' => 'مرزیکلا'],
            ['province_id' => 27, 'county_id' => 366, 'name' => 'بابلسر'],
            ['province_id' => 27, 'county_id' => 366, 'name' => 'بهنمیر'],
            ['province_id' => 27, 'county_id' => 366, 'name' => 'هادی شهر'],
            ['province_id' => 27, 'county_id' => 367, 'name' => 'بهشهر'],
            ['province_id' => 27, 'county_id' => 367, 'name' => 'خلیل شهر'],
            ['province_id' => 27, 'county_id' => 367, 'name' => 'رستمکلا'],
            ['province_id' => 27, 'county_id' => 368, 'name' => 'تنکابن'],
            ['province_id' => 27, 'county_id' => 368, 'name' => 'خرم آباد'],
            ['province_id' => 27, 'county_id' => 368, 'name' => 'شیرود'],
            ['province_id' => 27, 'county_id' => 368, 'name' => 'نشتارود'],
            ['province_id' => 27, 'county_id' => 369, 'name' => 'جویبار'],
            ['province_id' => 27, 'county_id' => 369, 'name' => 'کوهی خیل'],
            ['province_id' => 27, 'county_id' => 370, 'name' => 'چالوس'],
            ['province_id' => 27, 'county_id' => 370, 'name' => 'مرزن آباد'],
            ['province_id' => 27, 'county_id' => 370, 'name' => 'هچیرود'],
            ['province_id' => 27, 'county_id' => 371, 'name' => 'رامسر'],
            ['province_id' => 27, 'county_id' => 371, 'name' => 'کتالم وسادات شهر'],
            ['province_id' => 27, 'county_id' => 372, 'name' => 'پایین هولار'],
            ['province_id' => 27, 'county_id' => 372, 'name' => 'ساری'],
            ['province_id' => 27, 'county_id' => 372, 'name' => 'فریم'],
            ['province_id' => 27, 'county_id' => 372, 'name' => 'کیاسر'],
            ['province_id' => 27, 'county_id' => 373, 'name' => 'آلاشت'],
            ['province_id' => 27, 'county_id' => 373, 'name' => 'پل سفید'],
            ['province_id' => 27, 'county_id' => 373, 'name' => 'زیرآب'],
            ['province_id' => 27, 'county_id' => 374, 'name' => 'شیرگاه'],
            ['province_id' => 27, 'county_id' => 375, 'name' => 'کیاکلا'],
            ['province_id' => 27, 'county_id' => 376, 'name' => 'سلمان شهر'],
            ['province_id' => 27, 'county_id' => 376, 'name' => 'عباس اباد'],
            ['province_id' => 27, 'county_id' => 376, 'name' => 'کلارآباد'],
            ['province_id' => 27, 'county_id' => 377, 'name' => 'فریدونکنار'],
            ['province_id' => 27, 'county_id' => 378, 'name' => 'ارطه'],
            ['province_id' => 27, 'county_id' => 378, 'name' => 'قایم شهر'],
            ['province_id' => 27, 'county_id' => 379, 'name' => 'کلاردشت'],
            ['province_id' => 27, 'county_id' => 380, 'name' => 'گلوگاه'],
            ['province_id' => 27, 'county_id' => 381, 'name' => 'سرخرود'],
            ['province_id' => 27, 'county_id' => 381, 'name' => 'محمودآباد'],
            ['province_id' => 27, 'county_id' => 382, 'name' => 'سورک'],
            ['province_id' => 27, 'county_id' => 383, 'name' => 'نکا'],
            ['province_id' => 27, 'county_id' => 384, 'name' => 'ایزدشهر'],
            ['province_id' => 27, 'county_id' => 384, 'name' => 'بلده'],
            ['province_id' => 27, 'county_id' => 384, 'name' => 'چمستان'],
            ['province_id' => 27, 'county_id' => 384, 'name' => 'رویان'],
            ['province_id' => 27, 'county_id' => 384, 'name' => 'نور'],
            ['province_id' => 27, 'county_id' => 385, 'name' => 'پول'],
            ['province_id' => 27, 'county_id' => 385, 'name' => 'کجور'],
            ['province_id' => 27, 'county_id' => 385, 'name' => 'نوشهر'],
            ['province_id' => 28, 'county_id' => 386, 'name' => 'آشتیان'],
            ['province_id' => 28, 'county_id' => 387, 'name' => 'اراک'],
            ['province_id' => 28, 'county_id' => 387, 'name' => 'داودآباد'],
            ['province_id' => 28, 'county_id' => 387, 'name' => 'ساروق'],
            ['province_id' => 28, 'county_id' => 387, 'name' => 'کارچان'],
            ['province_id' => 28, 'county_id' => 388, 'name' => 'تفرش'],
            ['province_id' => 28, 'county_id' => 389, 'name' => 'خمین'],
            ['province_id' => 28, 'county_id' => 389, 'name' => 'قورچی باشی'],
            ['province_id' => 28, 'county_id' => 390, 'name' => 'جاورسیان'],
            ['province_id' => 28, 'county_id' => 390, 'name' => 'خنداب'],
            ['province_id' => 28, 'county_id' => 391, 'name' => 'دلیجان'],
            ['province_id' => 28, 'county_id' => 391, 'name' => 'نراق'],
            ['province_id' => 28, 'county_id' => 392, 'name' => 'پرندک'],
            ['province_id' => 28, 'county_id' => 392, 'name' => 'خشکرود'],
            ['province_id' => 28, 'county_id' => 392, 'name' => 'رازقان'],
            ['province_id' => 28, 'county_id' => 392, 'name' => 'زاویه'],
            ['province_id' => 28, 'county_id' => 392, 'name' => 'مامونیه'],
            ['province_id' => 28, 'county_id' => 393, 'name' => 'آوه'],
            ['province_id' => 28, 'county_id' => 393, 'name' => 'ساوه'],
            ['province_id' => 28, 'county_id' => 393, 'name' => 'غرق آباد'],
            ['province_id' => 28, 'county_id' => 393, 'name' => 'نوبران'],
            ['province_id' => 28, 'county_id' => 394, 'name' => 'آستانه'],
            ['province_id' => 28, 'county_id' => 394, 'name' => 'توره'],
            ['province_id' => 28, 'county_id' => 394, 'name' => 'شازند'],
            ['province_id' => 28, 'county_id' => 394, 'name' => 'شهباز'],
            ['province_id' => 28, 'county_id' => 394, 'name' => 'مهاجران'],
            ['province_id' => 28, 'county_id' => 394, 'name' => 'هندودر'],
            ['province_id' => 28, 'county_id' => 395, 'name' => 'خنجین'],
            ['province_id' => 28, 'county_id' => 395, 'name' => 'فرمهین'],
            ['province_id' => 28, 'county_id' => 396, 'name' => 'کمیجان'],
            ['province_id' => 28, 'county_id' => 396, 'name' => 'میلاجرد'],
            ['province_id' => 28, 'county_id' => 397, 'name' => 'محلات'],
            ['province_id' => 28, 'county_id' => 397, 'name' => 'نیمور'],
            ['province_id' => 29, 'county_id' => 398, 'name' => 'ابوموسی'],
            ['province_id' => 29, 'county_id' => 399, 'name' => 'بستک'],
            ['province_id' => 29, 'county_id' => 399, 'name' => 'جناح'],
            ['province_id' => 29, 'county_id' => 400, 'name' => 'سردشت'],
            ['province_id' => 29, 'county_id' => 400, 'name' => 'گوهران'],
            ['province_id' => 29, 'county_id' => 401, 'name' => 'بندرعباس'],
            ['province_id' => 29, 'county_id' => 401, 'name' => 'تازیان پایین'],
            ['province_id' => 29, 'county_id' => 401, 'name' => 'تخت'],
            ['province_id' => 29, 'county_id' => 401, 'name' => 'فین'],
            ['province_id' => 29, 'county_id' => 401, 'name' => 'قلعه قاضی'],
            ['province_id' => 29, 'county_id' => 402, 'name' => 'بندرلنگه'],
            ['province_id' => 29, 'county_id' => 402, 'name' => 'چارک'],
            ['province_id' => 29, 'county_id' => 402, 'name' => 'کنگ'],
            ['province_id' => 29, 'county_id' => 402, 'name' => 'کیش'],
            ['province_id' => 29, 'county_id' => 402, 'name' => 'لمزان'],
            ['province_id' => 29, 'county_id' => 403, 'name' => 'پارسیان'],
            ['province_id' => 29, 'county_id' => 403, 'name' => 'دشتی'],
            ['province_id' => 29, 'county_id' => 403, 'name' => 'کوشکنار'],
            ['province_id' => 29, 'county_id' => 404, 'name' => 'بندرجاسک'],
            ['province_id' => 29, 'county_id' => 405, 'name' => 'حاجی اباد'],
            ['province_id' => 29, 'county_id' => 405, 'name' => 'سرگز'],
            ['province_id' => 29, 'county_id' => 405, 'name' => 'فارغان'],
            ['province_id' => 29, 'county_id' => 406, 'name' => 'خمیر'],
            ['province_id' => 29, 'county_id' => 406, 'name' => 'رویدر'],
            ['province_id' => 29, 'county_id' => 407, 'name' => 'بیکاء'],
            ['province_id' => 29, 'county_id' => 407, 'name' => 'دهبارز'],
            ['province_id' => 29, 'county_id' => 407, 'name' => 'زیارتعلی'],
            ['province_id' => 29, 'county_id' => 408, 'name' => 'سیریک'],
            ['province_id' => 29, 'county_id' => 408, 'name' => 'کوهستک'],
            ['province_id' => 29, 'county_id' => 408, 'name' => 'گروک'],
            ['province_id' => 29, 'county_id' => 409, 'name' => 'درگهان'],
            ['province_id' => 29, 'county_id' => 409, 'name' => 'سوزا'],
            ['province_id' => 29, 'county_id' => 409, 'name' => 'قشم'],
            ['province_id' => 29, 'county_id' => 409, 'name' => 'هرمز'],
            ['province_id' => 29, 'county_id' => 410, 'name' => 'تیرور'],
            ['province_id' => 29, 'county_id' => 410, 'name' => 'سندرک'],
            ['province_id' => 29, 'county_id' => 410, 'name' => 'میناب'],
            ['province_id' => 29, 'county_id' => 410, 'name' => 'هشتبندی'],
            ['province_id' => 30, 'county_id' => 411, 'name' => 'آجین'],
            ['province_id' => 30, 'county_id' => 411, 'name' => 'اسدآباد'],
            ['province_id' => 30, 'county_id' => 412, 'name' => 'بهار'],
            ['province_id' => 30, 'county_id' => 412, 'name' => 'صالح آباد'],
            ['province_id' => 30, 'county_id' => 412, 'name' => 'لالجین'],
            ['province_id' => 30, 'county_id' => 412, 'name' => 'مهاجران'],
            ['province_id' => 30, 'county_id' => 413, 'name' => 'تویسرکان'],
            ['province_id' => 30, 'county_id' => 413, 'name' => 'سرکان'],
            ['province_id' => 30, 'county_id' => 413, 'name' => 'فرسفج'],
            ['province_id' => 30, 'county_id' => 414, 'name' => 'دمق'],
            ['province_id' => 30, 'county_id' => 414, 'name' => 'رزن'],
            ['province_id' => 30, 'county_id' => 414, 'name' => 'قروه درجزین'],
            ['province_id' => 30, 'county_id' => 415, 'name' => 'فامنین'],
            ['province_id' => 30, 'county_id' => 416, 'name' => 'شیرین سو'],
            ['province_id' => 30, 'county_id' => 416, 'name' => 'کبودرآهنگ'],
            ['province_id' => 30, 'county_id' => 416, 'name' => 'گل تپه'],
            ['province_id' => 30, 'county_id' => 417, 'name' => 'ازندریان'],
            ['province_id' => 30, 'county_id' => 417, 'name' => 'جوکار'],
            ['province_id' => 30, 'county_id' => 417, 'name' => 'زنگنه'],
            ['province_id' => 30, 'county_id' => 417, 'name' => 'سامن'],
            ['province_id' => 30, 'county_id' => 417, 'name' => 'ملایر'],
            ['province_id' => 30, 'county_id' => 418, 'name' => 'برزول'],
            ['province_id' => 30, 'county_id' => 418, 'name' => 'فیروزان'],
            ['province_id' => 30, 'county_id' => 418, 'name' => 'گیان'],
            ['province_id' => 30, 'county_id' => 418, 'name' => 'نهاوند'],
            ['province_id' => 30, 'county_id' => 419, 'name' => 'جورقان'],
            ['province_id' => 30, 'county_id' => 419, 'name' => 'قهاوند'],
            ['province_id' => 30, 'county_id' => 419, 'name' => 'مریانج'],
            ['province_id' => 30, 'county_id' => 419, 'name' => 'همدان'],
            ['province_id' => 31, 'county_id' => 420, 'name' => 'ابرکوه'],
            ['province_id' => 31, 'county_id' => 420, 'name' => 'مهردشت'],
            ['province_id' => 31, 'county_id' => 421, 'name' => 'احمدآباد'],
            ['province_id' => 31, 'county_id' => 421, 'name' => 'اردکان'],
            ['province_id' => 31, 'county_id' => 421, 'name' => 'عقدا'],
            ['province_id' => 31, 'county_id' => 422, 'name' => 'اشکذر'],
            ['province_id' => 31, 'county_id' => 422, 'name' => 'خضرآباد'],
            ['province_id' => 31, 'county_id' => 423, 'name' => 'بافق'],
            ['province_id' => 31, 'county_id' => 424, 'name' => 'بهاباد'],
            ['province_id' => 31, 'county_id' => 425, 'name' => 'تفت'],
            ['province_id' => 31, 'county_id' => 425, 'name' => 'نیر'],
            ['province_id' => 31, 'county_id' => 426, 'name' => 'مروست'],
            ['province_id' => 31, 'county_id' => 426, 'name' => 'هرات'],
            ['province_id' => 31, 'county_id' => 427, 'name' => 'مهریز'],
            ['province_id' => 31, 'county_id' => 428, 'name' => 'بفروییه'],
            ['province_id' => 31, 'county_id' => 428, 'name' => 'میبد'],
            ['province_id' => 31, 'county_id' => 428, 'name' => 'ندوشن'],
            ['province_id' => 31, 'county_id' => 429, 'name' => 'حمیدیا'],
            ['province_id' => 31, 'county_id' => 429, 'name' => 'زارچ'],
            ['province_id' => 31, 'county_id' => 429, 'name' => 'شاهدیه'],
            ['province_id' => 31, 'county_id' => 429, 'name' => 'یزد']
        ];
        DB::table('cities')->insert($default_cities);

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('cities');
    }
}
